-- Curated Excel import: feste Polenläden DE
-- Source file: data/polenlaeden_feste_standorte_deutschland.xlsx
begin;
delete from public.places where source = 'curated';
create temporary table tmp_curated (slug text primary key, kind public.place_kind, lat float8, lng float8, street text, postal_code text, city text, state text, website text, opening_hours jsonb, tags text[], name_de text, name_pl text, desc_de text, desc_pl text, source_url text);
insert into tmp_curated values
('curated-xlsx-1-ropo-markt', 'shop'::public.place_kind, 48.754503, 8.5515762, 'Wilhelmstraße 89', '75323', 'Bad Wildbad', 'Baden-Württemberg', null, '{"raw": "Mo–Sa 09:00–19:00; So 10:00–18:00"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'RoPo Markt', 'RoPo Markt', 'Festes Geschäft mit rumänischem und polnischem Sortiment Polnische und rumänische Lebensmittel, Getränke, Süßwaren und Feinkost', 'Festes Geschäft mit rumänischem und polnischem Sortiment Polnische und rumänische Lebensmittel, Getränke, Süßwaren und Feinkost', 'https://web2.cylex.de/firma-home/ropo-markt--magazin-romanesc-polski-sklep--16789472.html'),
('curated-xlsx-2-lukullus-karlsruhe', 'shop'::public.place_kind, 49.0158964, 8.4225538, 'Klosterweg 10a', '76131', 'Karlsruhe', 'Baden-Württemberg', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Karlsruhe', 'Lukullus Karlsruhe', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 24.10.2019.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 24.10.2019.', 'https://lukullus-laden.eu/'),
('curated-xlsx-3-polskisklep-de-mannheim', 'shop'::public.place_kind, 49.5270941, 8.4875345, 'Hanauer Straße 25', '68305', 'Mannheim', 'Baden-Württemberg', 'https://polskisklep.de/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'PolskiSklep.de Mannheim', 'PolskiSklep.de Mannheim', 'Über 400 m²; Filiale seit 2017 Wurst, Fleisch, Milchprodukte, Fisch, Obst/Gemüse, Süßwaren, Konserven und Getränke Seit 2017.', 'Über 400 m²; Filiale seit 2017 Wurst, Fleisch, Milchprodukte, Fisch, Obst/Gemüse, Süßwaren, Konserven und Getränke Seit 2017.', 'https://polskisklep.de/'),
('curated-xlsx-4-polnische-spezialitaeten-grimm', 'shop'::public.place_kind, 48.7258147, 9.2725522, 'Herzog-Philipp-Platz 1', '73760', 'Ostfildern', 'Baden-Württemberg', 'https://www.polnische-spezialitäten-grimm.de/', '{"raw": "Mo–Mi 10:00–12:00 und 15:00–20:00; Do 09:00–14:00 und 15:00–20:00; Fr 09:00–20:00; Sa 09:00–18:00"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polnische Spezialitäten Grimm', 'Polnische Spezialitäten Grimm', 'Eingang über Robert-Koch-Straße; Paketversand nach Polen Polnische Spezialitäten und Lebensmittel', 'Eingang über Robert-Koch-Straße; Paketversand nach Polen Polnische Spezialitäten und Lebensmittel', 'https://www.polnische-spezialitäten-grimm.de/'),
('curated-xlsx-5-delicja-polnische-spezialitaeten', 'shop'::public.place_kind, 48.8909452, 8.6965215, 'Zerrennerstraße 26', '75172', 'Pforzheim', 'Baden-Württemberg', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Delicja Polnische Spezialitäten', 'Delicja Polnische Spezialitäten', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/delicja-polnische-spezialitaeten-16670359.html'),
('curated-xlsx-6-lukullus-stuttgart', 'shop'::public.place_kind, 48.8322935, 9.1865794, 'Erligheimer Straße 8', '70437', 'Stuttgart', 'Baden-Württemberg', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:30; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Stuttgart', 'Lukullus Stuttgart', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.10.2014.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.10.2014.', 'https://lukullus-laden.eu/'),
('curated-xlsx-7-lukullus-augsburg', 'shop'::public.place_kind, 48.3841506, 10.9214038, 'Klausstraße 24', '86167', 'Augsburg', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 10:00–20:00; Sa 10:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Augsburg', 'Lukullus Augsburg', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 19.03.2015.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 19.03.2015.', 'https://lukullus-laden.eu/'),
('curated-xlsx-8-lukullus-erlangen', 'shop'::public.place_kind, 49.5621721, 10.9616629, 'Sylvaniastraße 14', '91056', 'Erlangen', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Di 11:00–18:00; Mi–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Erlangen', 'Lukullus Erlangen', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.12.2021.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.12.2021.', 'https://lukullus-laden.eu/'),
('curated-xlsx-9-lukullus-landshut', 'shop'::public.place_kind, 48.5296389, 12.1461277, 'Innere Münchener Str. 18–20', '84036', 'Landshut', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Landshut', 'Lukullus Landshut', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 05.12.2019.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 05.12.2019.', 'https://lukullus-laden.eu/'),
('curated-xlsx-10-lukullus-muenchen-hadern', 'shop'::public.place_kind, 48.1193852, 11.483271, 'Guardinistraße 186', '81375', 'München', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus München-Hadern', 'Lukullus München-Hadern', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 18.07.2019.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 18.07.2019.', 'https://lukullus-laden.eu/'),
('curated-xlsx-11-lukullus-muenchen-hasenbergl', 'shop'::public.place_kind, 48.2074713, 11.552568, 'Rainfarnstraße 34', '80935', 'München', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus München-Hasenbergl', 'Lukullus München-Hasenbergl', 'Frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-12-ratibor-gabriela-s-polnische-spezialitaeten', 'shop'::public.place_kind, 49.4621674, 11.0224325, 'Fürther Straße 324', '90429', 'Nürnberg', 'Bayern', null, '{"raw": "Di–Fr 11:00–19:00; Sa 09:00–15:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Ratibor / Gabriela’s Polnische Spezialitäten', 'Ratibor / Gabriela’s Polnische Spezialitäten', 'Polnisch-schlesischer Spezialitätenladen Polnische und schlesische Lebensmittel, Getränke und Wurstwaren', 'Polnisch-schlesischer Spezialitätenladen Polnische und schlesische Lebensmittel, Getränke und Wurstwaren', 'https://www.google.com/search?q=Ratibor+Gabrielas+F%C3%BCrther+Stra%C3%9Fe+324+N%C3%BCrnberg'),
('curated-xlsx-13-lukullus-regensburg', 'shop'::public.place_kind, 49.0143786, 12.1180137, 'Greflinger Str. 53', '93055', 'Regensburg', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Di 10:00–18:00; Mi–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Regensburg', 'Lukullus Regensburg', 'Virtueller Rundgang; frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.11.2017.', 'Virtueller Rundgang; frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.11.2017.', 'https://lukullus-laden.eu/'),
('curated-xlsx-14-mini-center-shop-polnische-spezialitaeten', 'shop'::public.place_kind, 49.0076198, 13.2485938, 'Flanitzer Straße 20', '94227', 'Zwiesel', 'Bayern', 'https://minicentershop.de/', '{"raw": "Mo–Fr 10:00–19:00; Sa 09:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Mini Center Shop + Polnische Spezialitäten', 'Mini Center Shop + Polnische Spezialitäten', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://minicentershop.de/'),
('curated-xlsx-15-feinkost-bogocz-bistro-n-13', 'shop'::public.place_kind, 52.4161293, 13.4044131, 'Schlierbacher Weg 7–9', '12349', 'Berlin', 'Berlin', 'https://www.feinkost-bogocz.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Bogocz + Bistro N°13', 'Feinkost Bogocz + Bistro N°13', 'Feinkost, Catering, Plattenservice und polnischer Mittagstisch Polnische Feinkost, Wurst/Fleisch, warme Gerichte und Partyservice', 'Feinkost, Catering, Plattenservice und polnischer Mittagstisch Polnische Feinkost, Wurst/Fleisch, warme Gerichte und Partyservice', 'https://www.feinkost-bogocz.de/'),
('curated-xlsx-16-feinkost-haeusler-reinickendorf', 'shop'::public.place_kind, 52.567222, 13.362193, 'Residenzstraße 34', '13409', 'Berlin', 'Berlin', 'https://polskashop.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Häusler Reinickendorf', 'Feinkost Häusler Reinickendorf', 'In den Resi-Passagen Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'In den Resi-Passagen Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'https://polskashop.de/'),
('curated-xlsx-17-feinkost-haeusler-schoeneberg', 'shop'::public.place_kind, 52.5037904, 13.3445812, 'Bayreuther Straße 44', '10787', 'Berlin', 'Berlin', 'https://polskashop.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Häusler Schöneberg', 'Feinkost Häusler Schöneberg', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'https://polskashop.de/'),
('curated-xlsx-18-feinkost-haeusler-steglitz', 'shop'::public.place_kind, 52.455502, 13.3259094, 'Albrechtstraße 120', '12169', 'Berlin', 'Berlin', 'https://polskashop.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Häusler Steglitz', 'Feinkost Häusler Steglitz', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'https://polskashop.de/'),
('curated-xlsx-19-maly-ksiaze', 'shop'::public.place_kind, 52.4880745, 13.4075661, 'Lilienthalstraße 6', '10965', 'Berlin', 'Berlin', 'https://polnische-lebensmittel.berlin/', '{"raw": "Mo–Sa 10:00–20:00; So 10:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Mały Książę', 'Mały Książę', 'Laden und Café; DHL-Paketshop Pierogi, Suppen, Kuchen, Pfannkuchen, Wurst/Käse, Backwaren, Getränke und Spirituosen Seit seit ca. 2014.', 'Laden und Café; DHL-Paketshop Pierogi, Suppen, Kuchen, Pfannkuchen, Wurst/Käse, Backwaren, Getränke und Spirituosen Seit seit ca. 2014.', 'https://polnische-lebensmittel.berlin/'),
('curated-xlsx-20-polski-sklep-dosia', 'shop'::public.place_kind, 52.4254275, 13.4630198, 'Lipschitzallee 68', '12353', 'Berlin', 'Berlin', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–14:00; So 10:00–12:30"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep DOSIA', 'Polski Sklep DOSIA', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-dosia-13284424.html'),
('curated-xlsx-21-u-zosi-spandau', 'shop'::public.place_kind, 52.536032, 13.2039749, 'Breite Straße 63', '13597', 'Berlin', 'Berlin', 'https://www.instagram.com/u_zosi_berlin/', '{"raw": "Mo–Fr 09:00–20:00; Sa 10:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'U Zosi – Spandau', 'U Zosi – Spandau', 'Zweite Berliner Filiale laut Social-Media-Profil Polnische Lebensmittel und Spezialitäten', 'Zweite Berliner Filiale laut Social-Media-Profil Polnische Lebensmittel und Spezialitäten', 'https://www.instagram.com/u_zosi_berlin/'),
('curated-xlsx-22-u-zosi-turmstrasse', 'shop'::public.place_kind, 52.5264816, 13.3506918, 'Turmstraße 13', '10559', 'Berlin', 'Berlin', 'https://www.instagram.com/u_zosi_berlin/', '{"raw": "Mo–Fr 08:00–21:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'U Zosi – Turmstraße', 'U Zosi – Turmstraße', 'Polnischer Nachbarschaftsladen; bereits 2009 erwähnt Polnische Lebensmittel und Spezialitäten Seit seit 2009 oder früher.', 'Polnischer Nachbarschaftsladen; bereits 2009 erwähnt Polnische Lebensmittel und Spezialitäten Seit seit 2009 oder früher.', 'https://www.instagram.com/u_zosi_berlin/'),
('curated-xlsx-23-polnische-feinkost-cottbus', 'shop'::public.place_kind, 51.7632033, 14.346869, 'Hermannstraße 12', '03042', 'Cottbus', 'Brandenburg', 'https://polnische-feinkost-cottbus.de/', '{"raw": "Mo 09:00–18:00; Di 09:00–14:00; Mi 09:00–18:00; Do 09:00–14:00; Fr 09:00–13:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Feinkost Cottbus', 'Polnische Feinkost Cottbus', 'Kleiner polnischer Feinkostladen Polnische Lebensmittel und Feinkost', 'Kleiner polnischer Feinkostladen Polnische Lebensmittel und Feinkost', 'https://polnische-feinkost-cottbus.de/'),
('curated-xlsx-24-gucio-polnische-spezialitaeten', 'shop'::public.place_kind, 53.0863872, 8.8894697, 'August-Bebel-Allee 298', '28329', 'Bremen', 'Bremen', 'https://gucio.de/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'GUCIO Polnische Spezialitäten', 'GUCIO Polnische Spezialitäten', 'Polnischer Spezialitätenmarkt Wurstwaren, polnische Lebensmittel sowie saisonales Obst und Gemüse', 'Polnischer Spezialitätenmarkt Wurstwaren, polnische Lebensmittel sowie saisonales Obst und Gemüse', 'https://gucio.de/'),
('curated-xlsx-25-polnische-spezialitaeten-bremen-huchting', 'shop'::public.place_kind, 53.0437994, 8.7227246, 'Nimweger Straße 2', '28259', 'Bremen', 'Bremen', 'https://www.instagram.com/polnische_spezialitaeten_bremen/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00 (Profilangabe)"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Bremen-Huchting', 'Polnische Spezialitäten Bremen-Huchting', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'https://www.instagram.com/polnische_spezialitaeten_bremen/'),
('curated-xlsx-26-polnische-spezialitaeten-bremen-nord', 'shop'::public.place_kind, 53.1802287, 8.7144002, 'Stockholmer Straße 8', '28719', 'Bremen', 'Bremen', 'https://www.instagram.com/polnische_spezialitaeten_bremen/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00 (Profilangabe)"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Bremen-Nord', 'Polnische Spezialitäten Bremen-Nord', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'https://www.instagram.com/polnische_spezialitaeten_bremen/'),
('curated-xlsx-27-polnische-spezialitaeten-bremen-osterholz', 'shop'::public.place_kind, 53.0718703, 8.9510472, 'Graubündener Straße 83', '28325', 'Bremen', 'Bremen', 'https://www.instagram.com/polnische_spezialitaeten_bremen/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00 (Profilangabe)"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Bremen-Osterholz', 'Polnische Spezialitäten Bremen-Osterholz', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'https://www.instagram.com/polnische_spezialitaeten_bremen/'),
('curated-xlsx-28-agat-polnische-spezialitaeten', 'shop'::public.place_kind, 53.5910812, 8.6185026, 'Wilhelm-Leuschner-Straße 1b–c', '27578', 'Bremerhaven', 'Bremen', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'AGAT Polnische Spezialitäten', 'AGAT Polnische Spezialitäten', 'Traditionelle Wurstwaren, polnische Süßwaren und schlesische Fleischspezialitäten', 'Traditionelle Wurstwaren, polnische Süßwaren und schlesische Fleischspezialitäten', 'https://web2.cylex.de/firma-home/agat-gmbh-polnische-spezialitaeten-10150053.html'),
('curated-xlsx-29-delicje-delikatessen', 'shop'::public.place_kind, 53.5047567, 10.2038463, 'Plettenbergstraße 2', '21031', 'Hamburg', 'Hamburg', 'https://www.facebook.com/delicjehamburg', '{"raw": "Mo–Fr 07:00–20:00; Sa 07:00–15:00; So 08:00–17:00"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Delicje Delikatessen', 'Delicje Delikatessen', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://www.facebook.com/delicjehamburg'),
('curated-xlsx-30-food-plus-polski-sklep-hamburg-harburg', 'shop'::public.place_kind, 53.461783, 9.9825052, 'Kleiner Schippsee 5', '21073', 'Hamburg', 'Hamburg', 'https://foodplus.eu/', '{"raw": "Mo–Fr 08:00–20:00; Sa 10:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Food Plus / Polski Sklep Hamburg-Harburg', 'Food Plus / Polski Sklep Hamburg-Harburg', 'Polnischer Lebensmittelladen Polnische Lebensmittel, Kühlware, Süßwaren und Getränke', 'Polnischer Lebensmittelladen Polnische Lebensmittel, Kühlware, Süßwaren und Getränke', 'https://foodplus.eu/'),
('curated-xlsx-31-promo-supermarkt-hamburg-jenfeld', 'shop'::public.place_kind, 53.5691915, 10.1346934, 'Öjendorfer Damm 38', '22043', 'Hamburg', 'Hamburg', 'https://supermarkt-promo.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'PROMO Supermarkt Hamburg-Jenfeld', 'PROMO Supermarkt Hamburg-Jenfeld', 'Kostenlose Parkplätze; Bäckerei und Frischetheken Polnische Lebensmittel, Fleisch/Wurst, Käse, Obst/Gemüse, Presse, Spirituosen und Haushaltswaren', 'Kostenlose Parkplätze; Bäckerei und Frischetheken Polnische Lebensmittel, Fleisch/Wurst, Käse, Obst/Gemüse, Presse, Spirituosen und Haushaltswaren', 'https://supermarkt-promo.de/'),
('curated-xlsx-32-polnische-spezialitaeten-kredens', 'shop'::public.place_kind, 53.4951041, 10.2055758, 'Lohbrügger Landstraße 11', '21031', 'Hamburg', 'Hamburg', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Kredens', 'Polnische Spezialitäten Kredens', 'Polnische Lebensmittel, Gemüse, Fleisch, Kuchen, Wurstwaren, Süßwaren, Kosmetik und Zeitschriften', 'Polnische Lebensmittel, Gemüse, Fleisch, Kuchen, Wurstwaren, Süßwaren, Kosmetik und Zeitschriften', 'https://lukullus-laden.eu/'),
('curated-xlsx-33-zagloba-billstedt', 'shop'::public.place_kind, 53.5392794, 10.1073627, 'Möllner Landstraße 31', '22111', 'Hamburg', 'Hamburg', 'https://zagloba.de/', '{"raw": "Mo–Do 10:00–18:00; Fr 10:00–19:00; Sa 10:00–15:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Zagłoba Billstedt', 'Zagłoba Billstedt', 'Polnischer Spezialitätenladen Polnische Lebensmittel, Wurstwaren, Getränke und Süßwaren', 'Polnischer Spezialitätenladen Polnische Lebensmittel, Wurstwaren, Getränke und Süßwaren', 'https://zagloba.de/'),
('curated-xlsx-34-prima-polnische-schlesische-feinkost', 'shop'::public.place_kind, 49.6829814, 8.6202809, 'Rodensteinstraße 7', '64625', 'Bensheim', 'Hessen', 'https://www.prima-polnische-und-schlesische-spezialitaten.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:30; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Prima Polnische & Schlesische Feinkost', 'Prima Polnische & Schlesische Feinkost', 'Im Neumarkt-Center Polnische und schlesische Feinkost, Wurstwaren, Backwaren und Spezialitäten', 'Im Neumarkt-Center Polnische und schlesische Feinkost, Wurstwaren, Backwaren und Spezialitäten', 'https://www.prima-polnische-und-schlesische-spezialitaten.de/'),
('curated-xlsx-35-promo-polski-supermarket-frankfurt', 'shop'::public.place_kind, 50.1376243, 8.6463407, 'Ginnheimer Landstraße 110', '60431', 'Frankfurt am Main', 'Hessen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Promo Polski Supermarket Frankfurt', 'Promo Polski Supermarket Frankfurt', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-36-promo-polski-supermarket-hanau', 'shop'::public.place_kind, 50.1416826, 8.9282801, 'Lamboystraße 11', '63452', 'Hanau', 'Hessen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Promo Polski Supermarket Hanau', 'Promo Polski Supermarket Hanau', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-37-smakosz-polski-sklep', 'shop'::public.place_kind, 50.0803507, 8.2247859, 'Blücherstraße 40', '65195', 'Wiesbaden', 'Hessen', 'https://polski-sklep-wiesbaden.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Smakosz – Polski Sklep', 'Smakosz – Polski Sklep', 'Frische Lieferungen dienstags und donnerstags Wurst/Fleisch, Brot/Backwaren, Pierogi, Süßwaren, Konserven, Getränke, Zeitschriften und Ziaja-Kosmetik Seit 28.06.2008.', 'Frische Lieferungen dienstags und donnerstags Wurst/Fleisch, Brot/Backwaren, Pierogi, Süßwaren, Konserven, Getränke, Zeitschriften und Ziaja-Kosmetik Seit 28.06.2008.', 'https://polski-sklep-wiesbaden.de/'),
('curated-xlsx-38-polnische-lebensmittel-demmin', 'shop'::public.place_kind, 53.9056687, 13.0428153, 'Gartenstraße 5', '17109', 'Demmin', 'Mecklenburg-Vorpommern', null, '{"raw": "Mo–Fr 09:00–16:00; Sa–So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polnische Lebensmittel Demmin', 'Polnische Lebensmittel Demmin', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://einkauflist.de/einrichtungen/polnische-lebensmittel/19606'),
('curated-xlsx-39-kowaliki-polski-sklep', 'shop'::public.place_kind, 52.5423009, 7.8640116, 'Alfons-Schulte-Straße 2', '49577', 'Ankum', 'Niedersachsen', null, '{"raw": "Mo geschlossen; Di 10:15–18:00; Mi 10:00–18:00; Do 10:00–18:30; Fr 10:15–18:30; Sa 09:00–15:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Kowaliki – Polski Sklep', 'Kowaliki – Polski Sklep', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/kowaliki---polski-sklep--polnischer-laden--15633825.html'),
('curated-xlsx-40-polski-sklep-bramsche', 'shop'::public.place_kind, 52.4109272, 7.9794238, 'Große Straße 46', '49565', 'Bramsche', 'Niedersachsen', null, '{"raw": "Mo–Fr 10:00–18:00; Sa 09:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep Bramsche', 'Polski Sklep Bramsche', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polnischer-laden--polski-sklep-bramsche-15024560.html'),
('curated-xlsx-41-wespol-polnische-spezialitaeten', 'shop'::public.place_kind, 52.2465188, 10.4873929, 'Donaustraße 44', '38120', 'Braunschweig', 'Niedersachsen', 'https://www.wespol-bs.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–13:30; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'WESPOL – Polnische Spezialitäten', 'WESPOL – Polnische Spezialitäten', 'Polnische Spezialitäten Polnische Lebensmittel und Feinkost', 'Polnische Spezialitäten Polnische Lebensmittel und Feinkost', 'https://www.wespol-bs.de/'),
('curated-xlsx-42-polnische-spezialitaeten-celle', 'shop'::public.place_kind, 52.6496058, 10.099103, 'Tannhorstfeld 1', '29229', 'Celle', 'Niedersachsen', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 08:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polnische Spezialitäten Celle', 'Polnische Spezialitäten Celle', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polnische-spezialitaeten-celle-15081219.html'),
('curated-xlsx-43-lukullus-garbsen', 'shop'::public.place_kind, 52.4390224, 9.6095294, 'Osterwalder Str. 10a', '30827', 'Garbsen', 'Niedersachsen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 08:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Garbsen', 'Lukullus Garbsen', 'Ca. 450 m², rund 50 Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Ca. 450 m², rund 50 Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-44-polski-sklep-kurpiak', 'shop'::public.place_kind, 52.4347083, 9.7219272, 'Hans-Böckler-Straße 8', '30851', 'Langenhagen', 'Niedersachsen', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep Kurpiak', 'Polski Sklep Kurpiak', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-kurpiak-16587127.html'),
('curated-xlsx-45-frischemarkt-sklep-polski-lueneburg', 'shop'::public.place_kind, 53.2461942, 10.4333966, 'Schützenstraße 98–99', '21337', 'Lüneburg', 'Niedersachsen', null, '{"raw": "Mo–Sa 07:00–20:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'FrischeMarkt – Sklep Polski Lüneburg', 'FrischeMarkt – Sklep Polski Lüneburg', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/frischemarkt---sklep-polski-lueneburg-13462559.html'),
('curated-xlsx-46-odra-deli', 'shop'::public.place_kind, 52.2947428, 8.0133276, 'Natruper Straße 230', '49090', 'Osnabrück', 'Niedersachsen', null, '{"raw": "Mo geschlossen; Di–Fr 10:00–18:30; Sa 09:00–15:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Odra Deli', 'Odra Deli', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-odra-deli-osnabrueck---polnischer-laden-odra-deli---osnabrueck-13487961.html'),
('curated-xlsx-47-beim-schlesier', 'shop'::public.place_kind, 50.8945947, 6.2823104, 'Kapellenplatz 12', '52457', 'Aldenhoven', 'Nordrhein-Westfalen', null, '{"raw": "Mo geschlossen; Di–Fr 10:00–18:00; Sa 09:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Beim Schlesier', 'Beim Schlesier', 'Polnische und schlesische Lebensmittel, Wurstwaren und Feinkost', 'Polnische und schlesische Lebensmittel, Wurstwaren und Feinkost', 'https://web2.cylex.de/firma-home/beim-schlesier--polski-sklep--polnisches-lebensmittel-10852472.html'),
('curated-xlsx-48-polonia-shop-bergheim', 'shop'::public.place_kind, 50.9458026, 6.6441119, 'Leipziger Straße 1/3', '50126', 'Bergheim', 'Nordrhein-Westfalen', 'https://polonia-shop.info/', '{"raw": "Mo–Sa 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polonia Shop Bergheim', 'Polonia Shop Bergheim', 'Ria-Geldtransfer; Versand nach Polen; barrierefrei; Kartenzahlung und Parkplätze Polnische Lebensmittel, Frischeprodukte, Getränke und Alltagswaren', 'Ria-Geldtransfer; Versand nach Polen; barrierefrei; Kartenzahlung und Parkplätze Polnische Lebensmittel, Frischeprodukte, Getränke und Alltagswaren', 'https://polonia-shop.info/'),
('curated-xlsx-49-lukullus-bielefeld', 'shop'::public.place_kind, 52.0245805, 8.5650171, 'Lohbreite 1', '33607', 'Bielefeld', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Di–Fr 10:00–18:00; Sa 09:00–15:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Bielefeld', 'Lukullus Bielefeld', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 31.05.2012.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 31.05.2012.', 'https://lukullus-laden.eu/'),
('curated-xlsx-50-polonia-market-bonn', 'shop'::public.place_kind, 50.7537013, 7.0730404, 'Kölnstraße 464', '53117', 'Bonn', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polonia Market Bonn', 'Polonia Market Bonn', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-51-polski-sklep-polka', 'shop'::public.place_kind, 50.8194392, 6.8925277, 'Römerstraße 1', '50321', 'Brühl', 'Nordrhein-Westfalen', null, '{"raw": "Mo–Sa 08:30–20:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep Polka', 'Polski Sklep Polka', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-polka-13758628.html'),
('curated-xlsx-52-polski-sklep-dormagen', 'shop'::public.place_kind, 51.0919782, 6.8431939, 'Kölner Straße 55', '41539', 'Dormagen', 'Nordrhein-Westfalen', 'https://www.polskisklep-dormagen.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep Dormagen', 'Polski Sklep Dormagen', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://www.polskisklep-dormagen.de/'),
('curated-xlsx-53-golly-s-dortmund-brackel', 'shop'::public.place_kind, 51.5225888, 7.5552772, 'Holzwickeder Str. 45', '44309', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-brackel-holzwickeder-str-45/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Golly’s Dortmund-Brackel', 'Golly’s Dortmund-Brackel', 'Kartenzahlung; Beratung; Frischetheke Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'Kartenzahlung; Beratung; Frischetheke Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'https://www.gollys.de/store/fachgeschaeft-dortmund-brackel-holzwickeder-str-45/'),
('curated-xlsx-54-golly-s-dortmund-scharnhorst', 'shop'::public.place_kind, 51.5577832, 7.5449732, 'Droote 56', '44328', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-droote-56/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Golly’s Dortmund-Scharnhorst', 'Golly’s Dortmund-Scharnhorst', 'Mittagstisch; seit 1996 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 1996.', 'Mittagstisch; seit 1996 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 1996.', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-droote-56/'),
('curated-xlsx-55-golly-s-dortmund-scharnhorst-eks', 'shop'::public.place_kind, 51.5520215, 7.54369, 'Gleiwitzstraße 271', '44328', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-eks-gleiwitzstrasse-271/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Golly’s Dortmund-Scharnhorst-EKS', 'Golly’s Dortmund-Scharnhorst-EKS', 'Im Einkaufszentrum Scharnhorst-EKS Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'Im Einkaufszentrum Scharnhorst-EKS Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-eks-gleiwitzstrasse-271/'),
('curated-xlsx-56-golly-s-dortmund-wickede', 'shop'::public.place_kind, 51.5323672, 7.6106967, 'Wickeder Hellweg 90', '44319', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-wickede-wickeder-hellweg-90/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Golly’s Dortmund-Wickede', 'Golly’s Dortmund-Wickede', 'Nahe U-Bahn; seit 2014 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 2014.', 'Nahe U-Bahn; seit 2014 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 2014.', 'https://www.gollys.de/store/fachgeschaeft-dortmund-wickede-wickeder-hellweg-90/'),
('curated-xlsx-57-lukullus-dortmund-unna', 'shop'::public.place_kind, 51.5358516, 7.6119783, 'Wickeder Straße 35', '44319', 'Dortmund', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Dortmund-Unna', 'Lukullus Dortmund-Unna', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 11.06.2012.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 11.06.2012.', 'https://lukullus-laden.eu/'),
('curated-xlsx-58-promo-polski-supermarket-dortmund', 'shop'::public.place_kind, 51.515648, 7.5041094, 'Körner Hellweg 47–49', '44143', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Promo Polski Supermarket Dortmund', 'Promo Polski Supermarket Dortmund', 'Große Getränkeauswahl Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Große Getränkeauswahl Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-59-promo-polski-supermarket-duisburg', 'shop'::public.place_kind, 51.4970582, 6.7986999, 'Hohenzollernplatz 16', '47167', 'Duisburg', 'Nordrhein-Westfalen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Promo Polski Supermarket Duisburg', 'Promo Polski Supermarket Duisburg', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-60-viktualia', 'shop'::public.place_kind, 51.4321668, 6.7632945, 'Wallstraße 8', '47051', 'Duisburg', 'Nordrhein-Westfalen', 'https://www.viktualia.eu/', '{"raw": "Mo–Fr 10:00–18:00; Sa 09:00–15:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Viktualia', 'Viktualia', 'Deutsch- und polnischsprachiges Team Polnische und schlesische Delikatessen, Wurst, Fleisch, Süßwaren und Feinkost Seit 2010.', 'Deutsch- und polnischsprachiges Team Polnische und schlesische Delikatessen, Wurst, Fleisch, Süßwaren und Feinkost Seit 2010.', 'https://www.viktualia.eu/'),
('curated-xlsx-61-lukullus-duesseldorf-garath', 'shop'::public.place_kind, 51.1430231, 6.8958276, 'Kurt-Schumacher-Str. 2', '40595', 'Düsseldorf', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Düsseldorf-Garath', 'Lukullus Düsseldorf-Garath', 'Kostenlose Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 04.04.2009.', 'Kostenlose Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 04.04.2009.', 'https://lukullus-laden.eu/'),
('curated-xlsx-62-polonia-market-essen-frohnhausen', 'shop'::public.place_kind, 51.4494145, 6.9711551, 'Frohnhauser Str. 282', '45144', 'Essen', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 08:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polonia Market Essen-Frohnhausen', 'Polonia Market Essen-Frohnhausen', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-63-polonia-market-essen-steele', 'shop'::public.place_kind, 51.4464148, 7.0502636, 'Steeler Str. 339', '45138', 'Essen', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polonia Market Essen-Steele', 'Polonia Market Essen-Steele', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-64-polonia-market-euskirchen', 'shop'::public.place_kind, 50.6665117, 6.7839524, 'Charleviller Platz 29', '53879', 'Euskirchen', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polonia Market Euskirchen', 'Polonia Market Euskirchen', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-65-lukullus-gelsenkirchen-beckhausen', 'shop'::public.place_kind, 51.5519731, 7.0442822, 'Horster Str. 350', '45899', 'Gelsenkirchen', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 10:00–17:00; Sa 10:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Gelsenkirchen-Beckhausen', 'Lukullus Gelsenkirchen-Beckhausen', 'Kostenlose Parkplätze gegenüber; Restaurant Janosik nebenan Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Kostenlose Parkplätze gegenüber; Restaurant Janosik nebenan Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-66-nasza-pszcz-lka', 'shop'::public.place_kind, 51.5200248, 7.1252872, 'Neuhüller Straße 38', '45888', 'Gelsenkirchen', 'Nordrhein-Westfalen', 'https://sellwerk.de/firmenprofil/nasza-pszczolka', '{"raw": "Mo–Sa 08:00–21:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Nasza Pszczółka', 'Nasza Pszczółka', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://sellwerk.de/firmenprofil/nasza-pszczolka'),
('curated-xlsx-67-lukullus-hagen-gevelsberg', 'shop'::public.place_kind, 51.3357654, 7.3825391, 'Hagener Str. 360', '58285', 'Gevelsberg', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Hagen-Gevelsberg', 'Lukullus Hagen-Gevelsberg', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 06.12.2018.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 06.12.2018.', 'https://lukullus-laden.eu/'),
('curated-xlsx-68-pol-markt-hagen', 'shop'::public.place_kind, 51.3801852, 7.477946, 'Boeler Straße 124', '58097', 'Hagen', 'Nordrhein-Westfalen', 'https://pol-markt.com/', '{"raw": "Mo–Fr 08:00–19:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'POL-MARKT Hagen', 'POL-MARKT Hagen', 'Großer polnischer Supermarkt Polnische/schlesische Wurst und Schinken, Gemüse, Kuchen, Gewürze, Süßwaren, Kosmetik und Haushaltswaren', 'Großer polnischer Supermarkt Polnische/schlesische Wurst und Schinken, Gemüse, Kuchen, Gewürze, Süßwaren, Kosmetik und Haushaltswaren', 'https://pol-markt.com/'),
('curated-xlsx-69-pola-market', 'shop'::public.place_kind, 51.7311982, 6.5897486, 'Marktstraße 19B', '46499', 'Hamminkeln', 'Nordrhein-Westfalen', 'https://polamarket.de/', '{"raw": "Mo 10:00–19:00; Di 10:00–19:00; Mi–Fr 09:00–19:00; Sa 10:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Pola Market', 'Pola Market', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://polamarket.de/'),
('curated-xlsx-70-polski-sklep-herford', 'shop'::public.place_kind, 52.1301128, 8.6985354, 'Amselplatz 1', '32049', 'Herford', 'Nordrhein-Westfalen', null, '{"raw": "Mo–Sa 08:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep Herford', 'Polski Sklep Herford', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-13195564.html'),
('curated-xlsx-71-anna-polnische-spezialitaeten', 'shop'::public.place_kind, 51.1807429, 6.9206953, 'Herderstraße 94', '40721', 'Hilden', 'Nordrhein-Westfalen', 'https://www.anzeiger24.de/hilden/Anna-Polnische-Spezialitaeten-Supermarkt', '{"raw": "Di–Fr 09:00–18:00; Sa 09:00–13:00; Mo laut Quelle geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Anna – Polnische Spezialitäten', 'Anna – Polnische Spezialitäten', 'Frischetheke; neuer Markt seit Sommer 2025 Pierogi, Wurst/Fleisch, Obst/Gemüse, Kuchen, Süßwaren, Getränke, Konserven, Gewürze und Saucen Seit Sommer 2025.', 'Frischetheke; neuer Markt seit Sommer 2025 Pierogi, Wurst/Fleisch, Obst/Gemüse, Kuchen, Süßwaren, Getränke, Konserven, Gewürze und Saucen Seit Sommer 2025.', 'https://www.anzeiger24.de/hilden/Anna-Polnische-Spezialitaeten-Supermarkt'),
('curated-xlsx-72-sklep-lasota-ham', 'shop'::public.place_kind, 51.3973312, 7.6936548, 'Giesestraße 3', '58636', 'Iserlohn', 'Nordrhein-Westfalen', 'https://lasotaham.de/', '{"raw": "Di–Fr 10:00–18:00; Sa 09:00–16:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Sklep Lasota HAM', 'Sklep Lasota HAM', 'Polnischer Spezialitätenladen Polnische Lebensmittel und Feinkost', 'Polnischer Spezialitätenladen Polnische Lebensmittel und Feinkost', 'https://lasotaham.de/'),
('curated-xlsx-73-promo-polski-supermarket-krefeld', 'shop'::public.place_kind, 51.3437421, 6.5514864, 'Hülser Straße 137–139', '47803', 'Krefeld', 'Nordrhein-Westfalen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 07:00–19:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Promo Polski Supermarket Krefeld', 'Promo Polski Supermarket Krefeld', 'Hauseigene Bäckerei; Spielecke für Kinder Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Hauseigene Bäckerei; Spielecke für Kinder Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-74-der-schlesier-koeln-porz', 'shop'::public.place_kind, 50.8840313, 7.0577138, 'Josefstraße 4', '51143', 'Köln', 'Nordrhein-Westfalen', null, '{"raw": "Mo 10:00–18:00; Di–Fr 09:30–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Der Schlesier Köln-Porz', 'Der Schlesier Köln-Porz', 'Polnisch-schlesischer Lebensmittelladen Polnische Lebensmittel und Getränke, Wurstwaren und Feinkost', 'Polnisch-schlesischer Lebensmittelladen Polnische Lebensmittel und Getränke, Wurstwaren und Feinkost', 'https://www.google.com/search?q=Der+Schlesier+Josefstra%C3%9Fe+4+K%C3%B6ln'),
('curated-xlsx-75-sobieski-polnische-spezialitaeten', 'shop'::public.place_kind, 50.9382686, 7.0042853, 'Kalker Hauptstraße 181', '51103', 'Köln', 'Nordrhein-Westfalen', 'https://www.facebook.com/SobieskiPolnischeSpezialitaten/', '{"raw": "Mo–Mi 09:00–20:00; Do 09:00–21:00; Fr 09:00–20:00; Sa 08:00–21:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Sobieski Polnische Spezialitäten', 'Sobieski Polnische Spezialitäten', 'Polnischer Supermarkt in Köln-Kalk Polnische Lebensmittel, Pierogi, Bigos, Wurst/Fleisch, Süßwaren und Getränke', 'Polnischer Supermarkt in Köln-Kalk Polnische Lebensmittel, Pierogi, Bigos, Wurst/Fleisch, Süßwaren und Getränke', 'https://www.facebook.com/SobieskiPolnischeSpezialitaten/'),
('curated-xlsx-76-lukullus-leverkusen-quettingen', 'shop'::public.place_kind, 51.0661263, 7.0278169, 'Lützenkirchener Str. 190', '51381', 'Leverkusen', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Leverkusen-Quettingen', 'Lukullus Leverkusen-Quettingen', 'Kostenlose Parkplätze; Geschenkkörbe, Gutscheine und kalte Platten Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 05.12.2009.', 'Kostenlose Parkplätze; Geschenkkörbe, Gutscheine und kalte Platten Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 05.12.2009.', 'https://lukullus-laden.eu/'),
('curated-xlsx-77-poloness-leverkusen', 'shop'::public.place_kind, 51.0609489, 7.0279256, 'Quettinger Str. 175', '51381', 'Leverkusen', 'Nordrhein-Westfalen', 'https://www.polones.de/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Poloness Leverkusen', 'Poloness Leverkusen', 'Polnische Spezialitäten; Filialbetrieb Polnische Lebensmittel und Feinkost', 'Polnische Spezialitäten; Filialbetrieb Polnische Lebensmittel und Feinkost', 'https://www.polones.de/'),
('curated-xlsx-78-lukullus-luedenscheid', 'shop'::public.place_kind, 51.2335114, 7.6209279, 'Im Olpendahl 4', '58507', 'Lüdenscheid', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Di–Fr 09:00–18:00; Sa 09:00–15:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Lüdenscheid', 'Lukullus Lüdenscheid', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 25.04.2013.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 25.04.2013.', 'https://lukullus-laden.eu/'),
('curated-xlsx-79-lukullus-moenchengladbach-rheydt', 'shop'::public.place_kind, 51.1671771, 6.4425227, 'Marktstraße 11', '41236', 'Mönchengladbach', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Mönchengladbach-Rheydt', 'Lukullus Mönchengladbach-Rheydt', 'Frische Lieferungen aus Polen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 21.11.2013.', 'Frische Lieferungen aus Polen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 21.11.2013.', 'https://lukullus-laden.eu/'),
('curated-xlsx-80-polonia-market-moenchengladbach', 'shop'::public.place_kind, 51.2051997, 6.4464173, 'Eickener Str. 158', '41063', 'Mönchengladbach', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polonia Market Mönchengladbach', 'Polonia Market Mönchengladbach', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-81-schlesische-spezialitaeten-polnische-delikatesse', 'shop'::public.place_kind, 51.1927945, 6.4418761, 'Lüpertzender Straße 124–126', '41061', 'Mönchengladbach', 'Nordrhein-Westfalen', null, '{"raw": "Mo geschlossen; Di–Fr 09:30–18:00; Sa 09:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Schlesische Spezialitäten / Polnische Delikatessen', 'Schlesische Spezialitäten / Polnische Delikatessen', 'Polnische und schlesische Lebensmittel, Wurstwaren und Delikatessen', 'Polnische und schlesische Lebensmittel, Wurstwaren und Delikatessen', 'https://web2.cylex.de/firma-home/schlesische-spezialitaeten---polnische-delikatessen--polski-sklep-10785031.html'),
('curated-xlsx-82-lukullus-oberhausen', 'shop'::public.place_kind, 51.5167986, 6.8466252, 'Brandenburger Str. 1', '46145', 'Oberhausen', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–15:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Oberhausen', 'Lukullus Oberhausen', 'Wochenmarkt direkt vor dem Laden mittwochs und samstags Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Wochenmarkt direkt vor dem Laden mittwochs und samstags Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-83-lukullus-ratingen', 'shop'::public.place_kind, 51.2933612, 6.8178895, 'Berliner Platz 15', '40880', 'Ratingen', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–18:30; Sa 09:00–15:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Ratingen', 'Lukullus Ratingen', 'Im Mosaik-Center; kostenlose Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 02.10.2013.', 'Im Mosaik-Center; kostenlose Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 02.10.2013.', 'https://lukullus-laden.eu/'),
('curated-xlsx-84-golly-s-recklinghausen', 'shop'::public.place_kind, 51.6126498, 7.2063837, 'Dortmunder Straße 26', '45665', 'Recklinghausen', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-recklinghausen-dortmunder-strasse-26/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Golly’s Recklinghausen', 'Golly’s Recklinghausen', 'Fleischerei-Fachgeschäft Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'Fleischerei-Fachgeschäft Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'https://www.gollys.de/store/fachgeschaeft-recklinghausen-dortmunder-strasse-26/'),
('curated-xlsx-85-cafe-market-polonia-polski-sklep', 'shop'::public.place_kind, 51.857544, 8.2836646, 'Herzebrocker Straße 6', '33378', 'Rheda-Wiedenbrück', 'Nordrhein-Westfalen', null, '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–19:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Cafe Market Polonia – Polski Sklep', 'Cafe Market Polonia – Polski Sklep', 'Lebensmittelmarkt mit Café Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Lebensmittelmarkt mit Café Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/cafe-market-polonia-polski-sklep-katarzyna-tomaszewicz-13351543.html'),
('curated-xlsx-86-polnische-delikatessen-urszula-grubek', 'shop'::public.place_kind, 50.8868805, 8.028641, 'Hagener Straße 109', '57072', 'Siegen', 'Nordrhein-Westfalen', null, '{"raw": "Mo geschlossen; Di–Fr 10:00–18:00; Sa 10:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Delikatessen – Urszula Grubek', 'Polnische Delikatessen – Urszula Grubek', 'Polnische und schlesische Delikatessen, Wurstwaren und Feinkost', 'Polnische und schlesische Delikatessen, Wurstwaren und Feinkost', 'https://web2.cylex.de/firma-home/polnische-delikatessen-inh--urszula-grubek-13712473.html'),
('curated-xlsx-87-golly-s-unna', 'shop'::public.place_kind, 51.5514196, 7.6378183, 'Buderusstraße 19', '59427', 'Unna', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-unna-buderusstrasse-19/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Golly’s Unna', 'Golly’s Unna', 'Fleischerei-Fachgeschäft Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'Fleischerei-Fachgeschäft Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'https://www.gollys.de/store/fachgeschaeft-unna-buderusstrasse-19/'),
('curated-xlsx-88-eufooma-polski-sklep', 'shop'::public.place_kind, 51.3330365, 7.0286734, 'Heiligenhauser Straße 1', '42549', 'Velbert', 'Nordrhein-Westfalen', 'https://eufooma.de/', '{"raw": "Mo–Sa 08:00–20:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Eufooma Polski Sklep', 'Eufooma Polski Sklep', 'Supermarkt und Spezialitätenmarkt Polnische Lebensmittel, Desserts, Getränke, Süßwaren, Konserven, Suppen, Kaffee, Tee und Haushaltswaren', 'Supermarkt und Spezialitätenmarkt Polnische Lebensmittel, Desserts, Getränke, Süßwaren, Konserven, Suppen, Kaffee, Tee und Haushaltswaren', 'https://eufooma.de/'),
('curated-xlsx-89-polski-sklep-balgar', 'shop'::public.place_kind, 51.3323486, 7.0249118, 'Heiligenhauser Straße 41', '42549', 'Velbert', 'Nordrhein-Westfalen', null, '{"raw": "Mo 10:00–18:00; Di–Fr 09:30–18:00; Sa 08:30–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polski Sklep Balgar', 'Polski Sklep Balgar', 'Polnische und schlesische Lebensmittel und Spezialitäten', 'Polnische und schlesische Lebensmittel und Spezialitäten', 'https://web2.cylex.de/firma-home/polski-sklep-velbert---schlesische-spezialitaeten-balgar-12286808.html'),
('curated-xlsx-90-sklep-polski-majka', 'shop'::public.place_kind, 51.8555138, 8.5636374, 'Fürstenstraße 12', '33415', 'Verl', 'Nordrhein-Westfalen', null, '{"raw": "Mo–Di geschlossen; Mi–Fr 09:00–18:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Sklep Polski Majka', 'Sklep Polski Majka', 'Nur Mittwoch bis Samstag geöffnet Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Nur Mittwoch bis Samstag geöffnet Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/sklep-polski-majka---polnische-spezialitaeten-15484029.html'),
('curated-xlsx-91-mili-polnischer-supermarkt', 'shop'::public.place_kind, 51.2709147, 7.1965692, 'Alter Markt 9', '42275', 'Wuppertal', 'Nordrhein-Westfalen', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Mili Polnischer Supermarkt', 'Mili Polnischer Supermarkt', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://onlinestreet.de/poi/UmppSUpqQ3BQYWlLSXh6bWc3L3ZzUT09'),
('curated-xlsx-92-lukullus-mainz', 'shop'::public.place_kind, 50.0211224, 8.2160251, 'Am Lemmchen 31a', '55120', 'Mainz', 'Rheinland-Pfalz', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Mainz', 'Lukullus Mainz', 'Neuer Standort laut Filialseite Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Neuer Standort laut Filialseite Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-93-sklep-polski-delikatesy-marek', 'shop'::public.place_kind, 54.8053683, 9.4150459, 'Freyastraße 1', '24939', 'Flensburg', 'Schleswig-Holstein', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Sklep Polski Delikatesy Marek', 'Sklep Polski Delikatesy Marek', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/sklep-polski-delikatesy-marek-polnische-spezialitaeten-11606807.html'),
('curated-xlsx-94-polnische-delikatessen-u-mirka', 'shop'::public.place_kind, 54.3207643, 10.1209939, 'Boninstraße 44', '24114', 'Kiel', 'Schleswig-Holstein', 'https://polnische-delikatessen-kiel.de/', '{"raw": "Mo–Di 10:00–16:00; Mi–Do 10:00–18:00; Fr 10:00–17:00; Sa 10:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Delikatessen „u Mirka“', 'Polnische Delikatessen „u Mirka“', 'Seit fast 20 Jahren laut Selbstdarstellung Wurst, Milchprodukte, Obst/Gemüse, Brot/Kuchen, Getränke, Konserven, Tiefkühlware, Süßwaren, Kosmetik und Presse Seit ca. 2006.', 'Seit fast 20 Jahren laut Selbstdarstellung Wurst, Milchprodukte, Obst/Gemüse, Brot/Kuchen, Getränke, Konserven, Tiefkühlware, Süßwaren, Kosmetik und Presse Seit ca. 2006.', 'https://polnische-delikatessen-kiel.de/'),
('curated-xlsx-95-polnische-spezialitaeten-luebeck', 'shop'::public.place_kind, 53.8427569, 10.6357058, 'Andersenring 21', '23560', 'Lübeck', 'Schleswig-Holstein', 'https://www.facebook.com/polnischespezialitaetenluebeck/', '{"raw": "Mo–Fr 10:00–19:00; Sa 10:00–17:00 (Quellenabgleich)"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Lübeck', 'Polnische Spezialitäten Lübeck', 'Polnischer Lebensmittelladen Polnische Lebensmittel und Feinkost', 'Polnischer Lebensmittelladen Polnische Lebensmittel und Feinkost', 'https://www.facebook.com/polnischespezialitaetenluebeck/'),
('curated-xlsx-96-food-plus-polski-sklep-pinneberg', 'shop'::public.place_kind, 53.6643387, 9.792646, 'Elmshorner Straße 23', '25421', 'Pinneberg', 'Schleswig-Holstein', 'https://foodplus.eu/', '{"raw": "Mo 10:00–18:00; Di–Fr 08:00–20:00; Sa 10:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Food Plus / Polski Sklep Pinneberg', 'Food Plus / Polski Sklep Pinneberg', 'Polnischer Lebensmittelladen Polnische Lebensmittel, Kühlware, Süßwaren und Getränke', 'Polnischer Lebensmittelladen Polnische Lebensmittel, Kühlware, Süßwaren und Getränke', 'https://foodplus.eu/');

insert into public.places (
  slug, kind, status, lat, lng, street, postal_code, city, state,
  website, phone, opening_hours, tags, source, source_url, verified_at
)
select slug, kind, 'published', lat, lng, street, postal_code, city, state,
  website, null, opening_hours, tags, 'curated'::public.place_source, source_url, now()
from tmp_curated
on conflict (slug) do update set
  kind = excluded.kind, status = 'published', lat = excluded.lat, lng = excluded.lng,
  street = excluded.street, postal_code = excluded.postal_code, city = excluded.city,
  state = excluded.state, website = excluded.website,
  opening_hours = excluded.opening_hours, tags = excluded.tags, source = excluded.source,
  source_url = excluded.source_url, verified_at = now(), updated_at = now();

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'de', s.name_de, s.desc_de, '', s.name_de || ' | Alemniam', left(s.desc_de, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'pl', s.name_pl, s.desc_pl, '', s.name_pl || ' | Alemniam', left(s.desc_pl, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;

-- Drop OSM duplicates within ~120m of a curated shop (Excel is richer).
delete from public.places osm
where osm.source = 'osm'
  and exists (
    select 1 from public.places c
    where c.source = 'curated'
      and st_dwithin(osm.location, c.location, 120)
  );

commit;

