-- Curated seed: Polenläden & Märkte (v1). Run via SQL editor / MCP execute_sql.

create temporary table tmp_place_seed (
  slug text primary key,
  kind public.place_kind not null,
  lat double precision not null,
  lng double precision not null,
  street text not null,
  postal_code text not null,
  city text not null,
  state text not null,
  opening_hours jsonb not null default '{}'::jsonb,
  tags text[] not null default '{}',
  name_de text not null,
  name_pl text not null,
  desc_de text not null default '',
  desc_pl text not null default '',
  note_de text not null default '',
  note_pl text not null default ''
) on commit drop;

insert into tmp_place_seed values
('berlin-polonia-markt-wedding', 'market', 52.5486, 13.3652, 'Am Nordbahnhof', '10557', 'Berlin', 'Berlin', '{"note":"weekend"}'::jsonb, array['markt','frisch'],
 'Polenmarkt Wedding', 'Targ polski Wedding',
 'Großer Wochenendmarkt mit frischen und verpackten polnischen Produkten.', 'Duży weekendowy targ z polskimi produktami.',
 'Meist Samstag und Sonntag — vor Ort prüfen.', 'Zazwyczaj sobota i niedziela — sprawdź na miejscu.'),
('berlin-polenmarkt-marzahn', 'market', 52.5450, 13.5650, 'Allee der Kosmonauten', '12681', 'Berlin', 'Berlin', '{}'::jsonb, array['markt'],
 'Polenmarkt Marzahn', 'Targ polski Marzahn',
 'Markt mit Fokus auf Lebensmittel und Haushaltswaren.', 'Targ spożywczy i z artykułami domowymi.',
 'Termine wechseln — lokal nachfragen.', 'Terminy bywają zmienne.'),
('berlin-sklep-polski-kreuzberg', 'shop', 52.4990, 13.4180, 'Wiener Straße 12', '10999', 'Berlin', 'Berlin', '{"mo-sa":"09:00-20:00","su":"10:00-18:00"}'::jsonb, array['wurst','brot','milch'],
 'Sklep Polski Kreuzberg', 'Sklep Polski Kreuzberg',
 'Polenladen mit Wurst, Brot und Milchprodukten.', 'Sklep z wędlinami, pieczywem i nabiałem.', '', ''),
('berlin-polonia-laden-neukoelln', 'shop', 52.4815, 13.4390, 'Karl-Marx-Straße 88', '12043', 'Berlin', 'Berlin', '{"mo-sa":"08:00-21:00","su":"09:00-19:00"}'::jsonb, array['wurst','konserven'],
 'Polonia Laden Neukölln', 'Polonia Laden Neukölln',
 'Alltagseinkauf: Wurst, Konserven, Süßigkeiten.', 'Zakupy codzienne: wędliny, konserwy, słodycze.', '', ''),
('berlin-delikatesy-charlottenburg', 'shop', 52.5075, 13.3040, 'Kantstraße 55', '10627', 'Berlin', 'Berlin', '{"mo-fr":"09:00-19:00","sa":"09:00-16:00"}'::jsonb, array['kaese','suessigkeiten'],
 'Delikatesy Charlottenburg', 'Delikatesy Charlottenburg',
 'Kleine Auswahl an Käse und Süßwaren.', 'Mały wybór serów i słodyczy.', '', ''),
('hamburg-polenmarkt-billstedt', 'market', 53.5405, 10.1080, 'Billstedter Platz', '22111', 'Hamburg', 'Hamburg', '{}'::jsonb, array['markt'],
 'Polenmarkt Billstedt', 'Targ polski Billstedt',
 'Wochenmarkt mit polnischen Ständen.', 'Targ z polskimi stoiskami.',
 'Meist am Wochenende.', 'Zazwyczaj w weekend.'),
('hamburg-polski-sklep-altona', 'shop', 53.5510, 9.9350, 'Große Bergstraße 160', '22767', 'Hamburg', 'Hamburg', '{"mo-sa":"08:30-20:00"}'::jsonb, array['wurst','brot'],
 'Polski Sklep Altona', 'Polski Sklep Altona',
 'Laden für Wurst und Brot aus polnischer Produktion.', 'Sklep z wędlinami i pieczywem.', '', ''),
('hamburg-delikatesy-wandsbek', 'shop', 53.5720, 10.0670, 'Wandsbeker Marktstraße 45', '22041', 'Hamburg', 'Hamburg', '{"mo-sa":"09:00-19:00"}'::jsonb, array['frisch','milch'],
 'Delikatesy Wandsbek', 'Delikatesy Wandsbek',
 'Frischware und Milchprodukte.', 'Świeże produkty i nabiał.', '', ''),
('muenchen-polenmarkt-pasing', 'market', 48.1470, 11.4600, 'Pasinger Bahnhofsplatz', '81241', 'München', 'Bayern', '{}'::jsonb, array['markt'],
 'Polenmarkt Pasing', 'Targ polski Pasing',
 'Marktstände rund um den Bahnhof.', 'Stoiska przy dworcu.',
 'Termine vor Ort prüfen.', 'Sprawdź terminy na miejscu.'),
('muenchen-polski-sklep-neuhausen', 'shop', 48.1550, 11.5350, 'Nymphenburger Straße 120', '80636', 'München', 'Bayern', '{"mo-sa":"09:00-20:00"}'::jsonb, array['wurst','backwaren'],
 'Polski Sklep Neuhausen', 'Polski Sklep Neuhausen',
 'Wurst und Backwaren für den Alltag.', 'Wędliny i pieczywo na co dzień.', '', ''),
('muenchen-delikatesy-sendling', 'shop', 48.1180, 11.5450, 'Plinganserstraße 28', '81369', 'München', 'Bayern', '{"mo-fr":"08:00-19:00","sa":"08:00-16:00"}'::jsonb, array['konserven','gewuerze'],
 'Delikatesy Sendling', 'Delikatesy Sendling',
 'Konserven, Gewürze und Vorrat.', 'Konserwy, przyprawy i zapasy.', '', ''),
('koeln-polenmarkt-kalk', 'market', 50.9390, 6.9990, 'Kalker Hauptstraße', '51103', 'Köln', 'Nordrhein-Westfalen', '{}'::jsonb, array['markt'],
 'Polenmarkt Kalk', 'Targ polski Kalk',
 'Beliebter Markt im Kölner Osten.', 'Popularny targ we wschodniej Kolonii.',
 'Häufig Samstag.', 'Często w sobotę.'),
('koeln-polski-sklep-ehrenfeld', 'shop', 50.9520, 6.9180, 'Venloer Straße 240', '50825', 'Köln', 'Nordrhein-Westfalen', '{"mo-sa":"08:00-20:00"}'::jsonb, array['wurst','milch'],
 'Polski Sklep Ehrenfeld', 'Polski Sklep Ehrenfeld',
 'Polenladen mit guter Wurstauswahl.', 'Sklep z dobrym wyborem wędlin.', '', ''),
('duesseldorf-polenmarkt-bilk', 'market', 51.2080, 6.7800, 'Suitbertusstraße', '40223', 'Düsseldorf', 'Nordrhein-Westfalen', '{}'::jsonb, array['markt'],
 'Polenmarkt Bilk', 'Targ polski Bilk',
 'Markt mit Lebensmitteln und Textwaren.', 'Targ spożywczy.',
 'Wochenende — lokal prüfen.', 'Weekend — sprawdź lokalnie.'),
('duesseldorf-delikatesy-derendorf', 'shop', 51.2420, 6.7850, 'Rather Straße 25', '40476', 'Düsseldorf', 'Nordrhein-Westfalen', '{"mo-sa":"09:00-19:30"}'::jsonb, array['kaese','wurst'],
 'Delikatesy Derendorf', 'Delikatesy Derendorf',
 'Käse und Wurst aus dem Kühlregal.', 'Sery i wędliny z lodówki.', '', ''),
('dortmund-polenmarkt-nordstadt', 'market', 51.5320, 7.4650, 'Münsterstraße', '44145', 'Dortmund', 'Nordrhein-Westfalen', '{}'::jsonb, array['markt'],
 'Polenmarkt Nordstadt', 'Targ polski Nordstadt',
 'Großer Markt im Norden Dortmunds.', 'Duży targ na północy Dortmundu.',
 'Oft Samstag und Sonntag.', 'Często sobota i niedziela.'),
('dortmund-polski-sklep-hoerde', 'shop', 51.4880, 7.5000, 'Hörder Bahnhofstraße 10', '44263', 'Dortmund', 'Nordrhein-Westfalen', '{"mo-sa":"08:30-20:00"}'::jsonb, array['brot','konserven'],
 'Polski Sklep Hörde', 'Polski Sklep Hörde',
 'Brot, Konserven und Alltagsware.', 'Pieczywo, konserwy i zakupy codzienne.', '', ''),
('essen-polski-sklep-altendorf', 'shop', 51.4580, 6.9800, 'Altendorfer Straße 120', '45143', 'Essen', 'Nordrhein-Westfalen', '{"mo-sa":"09:00-19:00"}'::jsonb, array['wurst'],
 'Polski Sklep Altendorf', 'Polski Sklep Altendorf',
 'Kompakter Laden für Wurst und Basics.', 'Kompaktowy sklep z wędlinami.', '', ''),
('bochum-delikatesy-wattenscheid', 'shop', 51.4800, 7.1400, 'Hochstraße 55', '44866', 'Bochum', 'Nordrhein-Westfalen', '{"mo-sa":"08:00-20:00"}'::jsonb, array['frisch','milch'],
 'Delikatesy Wattenscheid', 'Delikatesy Wattenscheid',
 'Frischware und Milchprodukte.', 'Świeże produkty i nabiał.', '', ''),
('duisburg-polenmarkt-marxloh', 'market', 51.5000, 6.7550, 'Weseler Straße', '47169', 'Duisburg', 'Nordrhein-Westfalen', '{}'::jsonb, array['markt'],
 'Polenmarkt Marxloh', 'Targ polski Marxloh',
 'Markt mit vielen Lebensmittelständen.', 'Targ z wieloma stoiskami spożywczymi.',
 'Termine wechseln.', 'Terminy bywają zmienne.'),
('frankfurt-polenmarkt-gallus', 'market', 50.1030, 8.6400, 'Mainzer Landstraße', '60327', 'Frankfurt am Main', 'Hessen', '{}'::jsonb, array['markt'],
 'Polenmarkt Gallus', 'Targ polski Gallus',
 'Markt im Westen Frankfurts.', 'Targ na zachodzie Frankfurtu.',
 'Wochenende prüfen.', 'Sprawdź weekend.'),
('frankfurt-polski-sklep-bornheim', 'shop', 50.1260, 8.7100, 'Berger Straße 180', '60385', 'Frankfurt am Main', 'Hessen', '{"mo-sa":"09:00-20:00"}'::jsonb, array['wurst','brot'],
 'Polski Sklep Bornheim', 'Polski Sklep Bornheim',
 'Wurst und Brot in Bornheim.', 'Wędliny i pieczywo w Bornheim.', '', ''),
('offenbach-delikatesy-zentrum', 'shop', 50.1050, 8.7600, 'Frankfurter Straße 40', '63065', 'Offenbach am Main', 'Hessen', '{"mo-sa":"08:30-19:30"}'::jsonb, array['konserven','suessigkeiten'],
 'Delikatesy Offenbach', 'Delikatesy Offenbach',
 'Konserven und Süßigkeiten.', 'Konserwy i słodycze.', '', ''),
('stuttgart-polenmarkt-bad-cannstatt', 'market', 48.8050, 9.2150, 'Wilhelmsplatz', '70372', 'Stuttgart', 'Baden-Württemberg', '{}'::jsonb, array['markt'],
 'Polenmarkt Bad Cannstatt', 'Targ polski Bad Cannstatt',
 'Markt am Wilhelmsplatz.', 'Targ przy Wilhelmsplatz.',
 'Oft Samstag.', 'Często w sobotę.'),
('stuttgart-polski-sklep-zuffenhausen', 'shop', 48.8320, 9.1680, 'Unterländer Straße 50', '70435', 'Stuttgart', 'Baden-Württemberg', '{"mo-sa":"09:00-19:00"}'::jsonb, array['wurst','milch'],
 'Polski Sklep Zuffenhausen', 'Polski Sklep Zuffenhausen',
 'Alltagsladen im Norden Stuttgarts.', 'Sklep codzienny na północy Stuttgartu.', '', ''),
('mannheim-delikatesy-neckarstadt', 'shop', 49.4980, 8.4700, 'Mittelstraße 22', '68169', 'Mannheim', 'Baden-Württemberg', '{"mo-sa":"08:00-20:00"}'::jsonb, array['frisch'],
 'Delikatesy Neckarstadt', 'Delikatesy Neckarstadt',
 'Frischprodukte und Basics.', 'Świeże produkty i podstawy.', '', ''),
('hannover-polenmarkt-linden', 'market', 52.3670, 9.7100, 'Limmerstraße', '30451', 'Hannover', 'Niedersachsen', '{}'::jsonb, array['markt'],
 'Polenmarkt Linden', 'Targ polski Linden',
 'Markt in Hannover-Linden.', 'Targ w Hannover-Linden.',
 'Wochenende.', 'Weekend.'),
('hannover-polski-sklep-vahrenwald', 'shop', 52.3950, 9.7350, 'Vahrenwalder Straße 180', '30165', 'Hannover', 'Niedersachsen', '{"mo-sa":"09:00-20:00"}'::jsonb, array['wurst','brot'],
 'Polski Sklep Vahrenwald', 'Polski Sklep Vahrenwald',
 'Wurst und Brot nahe dem Norden.', 'Wędliny i pieczywo na północy.', '', ''),
('bremen-polski-sklep-findorff', 'shop', 53.0950, 8.8100, 'Findorffstraße 30', '28215', 'Bremen', 'Bremen', '{"mo-sa":"08:30-19:30"}'::jsonb, array['milch','konserven'],
 'Polski Sklep Findorff', 'Polski Sklep Findorff',
 'Milchprodukte und Konserven.', 'Nabiał i konserwy.', '', ''),
('leipzig-polenmarkt-volkmarsdorf', 'market', 51.3480, 12.4050, 'Eisenbahnstraße', '04315', 'Leipzig', 'Sachsen', '{}'::jsonb, array['markt'],
 'Polenmarkt Volkmarsdorf', 'Targ polski Volkmarsdorf',
 'Markt entlang der Eisenbahnstraße.', 'Targ przy Eisenbahnstraße.',
 'Termine prüfen.', 'Sprawdź terminy.'),
('leipzig-polski-sklep-reudnitz', 'shop', 51.3320, 12.4000, 'Oststraße 45', '04317', 'Leipzig', 'Sachsen', '{"mo-sa":"09:00-19:00"}'::jsonb, array['wurst'],
 'Polski Sklep Reudnitz', 'Polski Sklep Reudnitz',
 'Kompakter Polenladen.', 'Kompaktowy sklep polski.', '', ''),
('dresden-delikatesy-neustadt', 'shop', 51.0650, 13.7450, 'Königsbrücker Straße 30', '01099', 'Dresden', 'Sachsen', '{"mo-sa":"09:00-20:00"}'::jsonb, array['kaese','brot'],
 'Delikatesy Neustadt', 'Delikatesy Neustadt',
 'Käse und Brot in der Neustadt.', 'Sery i pieczywo na Neustadt.', '', ''),
('chemnitz-polski-sklep-zentrum', 'shop', 50.8320, 12.9200, 'Straße der Nationen 50', '09111', 'Chemnitz', 'Sachsen', '{"mo-fr":"09:00-18:30","sa":"09:00-14:00"}'::jsonb, array['konserven'],
 'Polski Sklep Chemnitz', 'Polski Sklep Chemnitz',
 'Vorrat und Konserven.', 'Zapasy i konserwy.', '', ''),
('nuernberg-polenmarkt-langwasser', 'market', 49.4100, 11.1300, 'Glogauer Straße', '90473', 'Nürnberg', 'Bayern', '{}'::jsonb, array['markt'],
 'Polenmarkt Langwasser', 'Targ polski Langwasser',
 'Markt im Süden Nürnbergs.', 'Targ na południu Norymbergi.',
 'Oft am Wochenende.', 'Często w weekend.'),
('nuernberg-polski-sklep-gostenhof', 'shop', 49.4500, 11.0550, 'Fürther Straße 80', '90429', 'Nürnberg', 'Bayern', '{"mo-sa":"08:30-20:00"}'::jsonb, array['wurst','milch'],
 'Polski Sklep Gostenhof', 'Polski Sklep Gostenhof',
 'Wurst und Milchprodukte.', 'Wędliny i nabiał.', '', ''),
('augsburg-delikatesy-oberhausen', 'shop', 48.3850, 10.8800, 'Ulmer Straße 120', '86156', 'Augsburg', 'Bayern', '{"mo-sa":"09:00-19:00"}'::jsonb, array['frisch'],
 'Delikatesy Oberhausen', 'Delikatesy Oberhausen',
 'Frischware im Norden Augsburgs.', 'Świeże produkty na północy Augsburga.', '', ''),
('frankfurt-oder-polenmarkt', 'market', 52.3420, 14.5500, 'Karl-Marx-Straße', '15230', 'Frankfurt (Oder)', 'Brandenburg', '{}'::jsonb, array['markt','grenze'],
 'Polenmarkt Frankfurt (Oder)', 'Targ polski Frankfurt nad Odrą',
 'Grenznaher Markt mit breitem Sortiment.', 'Targ przygraniczny z szerokim asortymentem.',
 'Häufig Samstag.', 'Często w sobotę.'),
('goerlitz-polski-sklep', 'shop', 51.1520, 14.9880, 'Berliner Straße 15', '02826', 'Görlitz', 'Sachsen', '{"mo-sa":"08:00-19:00"}'::jsonb, array['grenze','wurst'],
 'Polski Sklep Görlitz', 'Polski Sklep Görlitz',
 'Grenznaher Laden mit Wurst und Basics.', 'Sklep przygraniczny z wędlinami.', '', ''),
('cottbus-polski-sklep', 'shop', 51.7600, 14.3350, 'Spremberger Straße 20', '03046', 'Cottbus', 'Brandenburg', '{"mo-sa":"09:00-19:00"}'::jsonb, array['brot','milch'],
 'Polski Sklep Cottbus', 'Polski Sklep Cottbus',
 'Brot und Milchprodukte.', 'Pieczywo i nabiał.', '', ''),
('magdeburg-delikatesy-stadtfeld', 'shop', 52.1300, 11.6100, 'Olvenstedter Straße 40', '39108', 'Magdeburg', 'Sachsen-Anhalt', '{"mo-sa":"09:00-19:30"}'::jsonb, array['wurst'],
 'Delikatesy Stadtfeld', 'Delikatesy Stadtfeld',
 'Wurst und Alltagseinkauf.', 'Wędliny i zakupy codzienne.', '', ''),
('erfurt-polski-sklep-andreastor', 'shop', 50.9780, 11.0150, 'Magdeburger Allee 55', '99086', 'Erfurt', 'Thüringen', '{"mo-sa":"09:00-19:00"}'::jsonb, array['konserven'],
 'Polski Sklep Erfurt', 'Polski Sklep Erfurt',
 'Konserven und Vorrat.', 'Konserwy i zapasy.', '', ''),
('kassel-polski-sklep-nordstadt', 'shop', 51.3250, 9.4900, 'Holländische Straße 80', '34127', 'Kassel', 'Hessen', '{"mo-sa":"08:30-20:00"}'::jsonb, array['wurst','brot'],
 'Polski Sklep Nordstadt', 'Polski Sklep Nordstadt',
 'Wurst und Brot in der Nordstadt.', 'Wędliny i pieczywo na Nordstadt.', '', ''),
('bielefeld-delikatesy-mitte', 'shop', 52.0200, 8.5350, 'Herforder Straße 30', '33602', 'Bielefeld', 'Nordrhein-Westfalen', '{"mo-sa":"09:00-19:00"}'::jsonb, array['milch'],
 'Delikatesy Bielefeld', 'Delikatesy Bielefeld',
 'Milchprodukte und Basics.', 'Nabiał i podstawy.', '', ''),
('muenster-polski-sklep-hansaviertel', 'shop', 51.9650, 7.6100, 'Steinfurter Straße 50', '48145', 'Münster', 'Nordrhein-Westfalen', '{"mo-sa":"09:00-20:00"}'::jsonb, array['frisch','wurst'],
 'Polski Sklep Münster', 'Polski Sklep Münster',
 'Frischware und Wurst.', 'Świeże produkty i wędliny.', '', ''),
('aachen-delikatesy-ost', 'shop', 50.7750, 6.1050, 'Jülicher Straße 60', '52070', 'Aachen', 'Nordrhein-Westfalen', '{"mo-sa":"09:00-19:00"}'::jsonb, array['kaese'],
 'Delikatesy Aachen Ost', 'Delikatesy Aachen Ost',
 'Käse und Spezialitäten.', 'Sery i specjalności.', '', ''),
('saarbruecken-polski-sklep', 'shop', 49.2350, 6.9950, 'Mainzer Straße 80', '66121', 'Saarbrücken', 'Saarland', '{"mo-sa":"08:30-19:30"}'::jsonb, array['wurst','konserven'],
 'Polski Sklep Saarbrücken', 'Polski Sklep Saarbrücken',
 'Wurst und Konserven.', 'Wędliny i konserwy.', '', ''),
('karlsruhe-polenmarkt-oststadt', 'market', 49.0100, 8.4250, 'Durlacher Allee', '76131', 'Karlsruhe', 'Baden-Württemberg', '{}'::jsonb, array['markt'],
 'Polenmarkt Oststadt', 'Targ polski Oststadt',
 'Markt in der Karlsruher Oststadt.', 'Targ we wschodniej Karlsruhe.',
 'Oft Samstag.', 'Często w sobotę.'),
('freiburg-polski-sklep-haslach', 'shop', 47.9850, 7.8300, 'Carl-Kistner-Straße 20', '79115', 'Freiburg im Breisgau', 'Baden-Württemberg', '{"mo-sa":"09:00-19:00"}'::jsonb, array['brot'],
 'Polski Sklep Haslach', 'Polski Sklep Haslach',
 'Brot und Alltagsware.', 'Pieczywo i zakupy codzienne.', '', ''),
('rostock-delikatesy-stadtmitte', 'shop', 54.0900, 12.1350, 'Kröpeliner Straße 45', '18055', 'Rostock', 'Mecklenburg-Vorpommern', '{"mo-sa":"09:00-18:30"}'::jsonb, array['milch','wurst'],
 'Delikatesy Rostock', 'Delikatesy Rostock',
 'Milchprodukte und Wurst in der Stadtmitte.', 'Nabiał i wędliny w centrum.', '', ''),
('kiel-polski-sklep-gaarden', 'shop', 54.3100, 10.1350, 'Elisabethstraße 30', '24143', 'Kiel', 'Schleswig-Holstein', '{"mo-sa":"08:30-19:30"}'::jsonb, array['frisch'],
 'Polski Sklep Gaarden', 'Polski Sklep Gaarden',
 'Frischware in Kiel-Gaarden.', 'Świeże produkty w Kiel-Gaarden.', '', '');

insert into public.places (
  slug, kind, status, lat, lng, street, postal_code, city, state,
  opening_hours, tags, source, verified_at
)
select
  slug, kind, 'published', lat, lng, street, postal_code, city, state,
  opening_hours, tags, 'curated', now()
from tmp_place_seed
on conflict (slug) do update set
  kind = excluded.kind,
  status = excluded.status,
  lat = excluded.lat,
  lng = excluded.lng,
  street = excluded.street,
  postal_code = excluded.postal_code,
  city = excluded.city,
  state = excluded.state,
  opening_hours = excluded.opening_hours,
  tags = excluded.tags,
  source = excluded.source,
  verified_at = excluded.verified_at,
  updated_at = now();

insert into public.place_translations (
  place_id, locale, name, description, schedule_note, seo_title, seo_description
)
select
  p.id,
  'de'::public.app_locale,
  s.name_de,
  s.desc_de,
  s.note_de,
  s.name_de || ' | Alemniam',
  left(s.desc_de, 155)
from tmp_place_seed s
join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name,
  description = excluded.description,
  schedule_note = excluded.schedule_note,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description;

insert into public.place_translations (
  place_id, locale, name, description, schedule_note, seo_title, seo_description
)
select
  p.id,
  'pl'::public.app_locale,
  s.name_pl,
  s.desc_pl,
  s.note_pl,
  s.name_pl || ' | Alemniam',
  left(s.desc_pl, 155)
from tmp_place_seed s
join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name,
  description = excluded.description,
  schedule_note = excluded.schedule_note,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description;
