begin;
create temporary table tmp_curated (
slug text primary key, kind public.place_kind, lat float8, lng float8,
street text, postal_code text, city text, state text, website text,
opening_hours jsonb, tags text[], name_de text, name_pl text,
desc_de text, desc_pl text, source_url text);
insert into tmp_curated values
('curated-xlsx-25-polnische-spezialitaeten-bremen-huchting', 'shop'::public.place_kind, 53.0437994, 8.7227246, 'Nimweger Straße 2', '28259', 'Bremen', 'Bremen', 'https://www.instagram.com/polnische_spezialitaeten_bremen/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00 (Profilangabe)"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Bremen-Huchting', 'Polnische Spezialitäten Bremen-Huchting', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'https://www.instagram.com/polnische_spezialitaeten_bremen/'),
('curated-xlsx-26-polnische-spezialitaeten-bremen-nord', 'shop'::public.place_kind, 53.1802287, 8.7144002, 'Stockholmer Straße 8', '28719', 'Bremen', 'Bremen', 'https://www.instagram.com/polnische_spezialitaeten_bremen/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00 (Profilangabe)"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Bremen-Nord', 'Polnische Spezialitäten Bremen-Nord', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'https://www.instagram.com/polnische_spezialitaeten_bremen/'),
('curated-xlsx-27-polnische-spezialitaeten-bremen-osterholz', 'shop'::public.place_kind, 53.0718703, 8.9510472, 'Graubündener Straße 83', '28325', 'Bremen', 'Bremen', 'https://www.instagram.com/polnische_spezialitaeten_bremen/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00 (Profilangabe)"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Bremen-Osterholz', 'Polnische Spezialitäten Bremen-Osterholz', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'Eine von drei Bremer Filialen Polnische Lebensmittel und Feinkost', 'https://www.instagram.com/polnische_spezialitaeten_bremen/'),
('curated-xlsx-28-agat-polnische-spezialitaeten', 'shop'::public.place_kind, 53.5910812, 8.6185026, 'Wilhelm-Leuschner-Straße 1b–c', '27578', 'Bremerhaven', 'Bremen', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'AGAT Polnische Spezialitäten', 'AGAT Polnische Spezialitäten', 'Traditionelle Wurstwaren, polnische Süßwaren und schlesische Fleischspezialitäten', 'Traditionelle Wurstwaren, polnische Süßwaren und schlesische Fleischspezialitäten', 'https://web2.cylex.de/firma-home/agat-gmbh-polnische-spezialitaeten-10150053.html'),
('curated-xlsx-29-delicje-delikatessen', 'shop'::public.place_kind, 53.5047567, 10.2038463, 'Plettenbergstraße 2', '21031', 'Hamburg', 'Hamburg', 'https://www.facebook.com/delicjehamburg', '{"raw": "Mo–Fr 07:00–20:00; Sa 07:00–15:00; So 08:00–17:00"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Delicje Delikatessen', 'Delicje Delikatessen', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://www.facebook.com/delicjehamburg'),
('curated-xlsx-30-food-plus-polski-sklep-hamburg-harburg', 'shop'::public.place_kind, 53.461783, 9.9825052, 'Kleiner Schippsee 5', '21073', 'Hamburg', 'Hamburg', 'https://foodplus.eu/', '{"raw": "Mo–Fr 08:00–20:00; Sa 10:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Food Plus / Polski Sklep Hamburg-Harburg', 'Food Plus / Polski Sklep Hamburg-Harburg', 'Polnischer Lebensmittelladen Polnische Lebensmittel, Kühlware, Süßwaren und Getränke', 'Polnischer Lebensmittelladen Polnische Lebensmittel, Kühlware, Süßwaren und Getränke', 'https://foodplus.eu/'),
('curated-xlsx-31-promo-supermarkt-hamburg-jenfeld', 'shop'::public.place_kind, 53.5691915, 10.1346934, 'Öjendorfer Damm 38', '22043', 'Hamburg', 'Hamburg', 'https://supermarkt-promo.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–18:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'PROMO Supermarkt Hamburg-Jenfeld', 'PROMO Supermarkt Hamburg-Jenfeld', 'Kostenlose Parkplätze; Bäckerei und Frischetheken Polnische Lebensmittel, Fleisch/Wurst, Käse, Obst/Gemüse, Presse, Spirituosen und Haushaltswaren', 'Kostenlose Parkplätze; Bäckerei und Frischetheken Polnische Lebensmittel, Fleisch/Wurst, Käse, Obst/Gemüse, Presse, Spirituosen und Haushaltswaren', 'https://supermarkt-promo.de/'),
('curated-xlsx-32-polnische-spezialitaeten-kredens', 'shop'::public.place_kind, 53.4951041, 10.2055758, 'Lohbrügger Landstraße 11', '21031', 'Hamburg', 'Hamburg', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Spezialitäten Kredens', 'Polnische Spezialitäten Kredens', 'Polnische Lebensmittel, Gemüse, Fleisch, Kuchen, Wurstwaren, Süßwaren, Kosmetik und Zeitschriften', 'Polnische Lebensmittel, Gemüse, Fleisch, Kuchen, Wurstwaren, Süßwaren, Kosmetik und Zeitschriften', 'https://lukullus-laden.eu/'),
('curated-xlsx-33-zagloba-billstedt', 'shop'::public.place_kind, 53.5392794, 10.1073627, 'Möllner Landstraße 31', '22111', 'Hamburg', 'Hamburg', 'https://zagloba.de/', '{"raw": "Mo–Do 10:00–18:00; Fr 10:00–19:00; Sa 10:00–15:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Zagłoba Billstedt', 'Zagłoba Billstedt', 'Polnischer Spezialitätenladen Polnische Lebensmittel, Wurstwaren, Getränke und Süßwaren', 'Polnischer Spezialitätenladen Polnische Lebensmittel, Wurstwaren, Getränke und Süßwaren', 'https://zagloba.de/'),
('curated-xlsx-34-prima-polnische-schlesische-feinkost', 'shop'::public.place_kind, 49.6829814, 8.6202809, 'Rodensteinstraße 7', '64625', 'Bensheim', 'Hessen', 'https://www.prima-polnische-und-schlesische-spezialitaten.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:30; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Prima Polnische & Schlesische Feinkost', 'Prima Polnische & Schlesische Feinkost', 'Im Neumarkt-Center Polnische und schlesische Feinkost, Wurstwaren, Backwaren und Spezialitäten', 'Im Neumarkt-Center Polnische und schlesische Feinkost, Wurstwaren, Backwaren und Spezialitäten', 'https://www.prima-polnische-und-schlesische-spezialitaten.de/'),
('curated-xlsx-35-promo-polski-supermarket-frankfurt', 'shop'::public.place_kind, 50.1376243, 8.6463407, 'Ginnheimer Landstraße 110', '60431', 'Frankfurt am Main', 'Hessen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Promo Polski Supermarket Frankfurt', 'Promo Polski Supermarket Frankfurt', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-36-promo-polski-supermarket-hanau', 'shop'::public.place_kind, 50.1416826, 8.9282801, 'Lamboystraße 11', '63452', 'Hanau', 'Hessen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Promo Polski Supermarket Hanau', 'Promo Polski Supermarket Hanau', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-37-smakosz-polski-sklep', 'shop'::public.place_kind, 50.0803507, 8.2247859, 'Blücherstraße 40', '65195', 'Wiesbaden', 'Hessen', 'https://polski-sklep-wiesbaden.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Smakosz – Polski Sklep', 'Smakosz – Polski Sklep', 'Frische Lieferungen dienstags und donnerstags Wurst/Fleisch, Brot/Backwaren, Pierogi, Süßwaren, Konserven, Getränke, Zeitschriften und Ziaja-Kosmetik Seit 28.06.2008.', 'Frische Lieferungen dienstags und donnerstags Wurst/Fleisch, Brot/Backwaren, Pierogi, Süßwaren, Konserven, Getränke, Zeitschriften und Ziaja-Kosmetik Seit 28.06.2008.', 'https://polski-sklep-wiesbaden.de/'),
('curated-xlsx-38-polnische-lebensmittel-demmin', 'shop'::public.place_kind, 53.9056687, 13.0428153, 'Gartenstraße 5', '17109', 'Demmin', 'Mecklenburg-Vorpommern', null, '{"raw": "Mo–Fr 09:00–16:00; Sa–So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polnische Lebensmittel Demmin', 'Polnische Lebensmittel Demmin', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://einkauflist.de/einrichtungen/polnische-lebensmittel/19606'),
('curated-xlsx-39-kowaliki-polski-sklep', 'shop'::public.place_kind, 52.5423009, 7.8640116, 'Alfons-Schulte-Straße 2', '49577', 'Ankum', 'Niedersachsen', null, '{"raw": "Mo geschlossen; Di 10:15–18:00; Mi 10:00–18:00; Do 10:00–18:30; Fr 10:15–18:30; Sa 09:00–15:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Kowaliki – Polski Sklep', 'Kowaliki – Polski Sklep', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/kowaliki---polski-sklep--polnischer-laden--15633825.html'),
('curated-xlsx-40-polski-sklep-bramsche', 'shop'::public.place_kind, 52.4109272, 7.9794238, 'Große Straße 46', '49565', 'Bramsche', 'Niedersachsen', null, '{"raw": "Mo–Fr 10:00–18:00; Sa 09:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep Bramsche', 'Polski Sklep Bramsche', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polnischer-laden--polski-sklep-bramsche-15024560.html'),
('curated-xlsx-41-wespol-polnische-spezialitaeten', 'shop'::public.place_kind, 52.2465188, 10.4873929, 'Donaustraße 44', '38120', 'Braunschweig', 'Niedersachsen', 'https://www.wespol-bs.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–13:30; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'WESPOL – Polnische Spezialitäten', 'WESPOL – Polnische Spezialitäten', 'Polnische Spezialitäten Polnische Lebensmittel und Feinkost', 'Polnische Spezialitäten Polnische Lebensmittel und Feinkost', 'https://www.wespol-bs.de/'),
('curated-xlsx-42-polnische-spezialitaeten-celle', 'shop'::public.place_kind, 52.6496058, 10.099103, 'Tannhorstfeld 1', '29229', 'Celle', 'Niedersachsen', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 08:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polnische Spezialitäten Celle', 'Polnische Spezialitäten Celle', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polnische-spezialitaeten-celle-15081219.html'),
('curated-xlsx-43-lukullus-garbsen', 'shop'::public.place_kind, 52.4390224, 9.6095294, 'Osterwalder Str. 10a', '30827', 'Garbsen', 'Niedersachsen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 08:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Garbsen', 'Lukullus Garbsen', 'Ca. 450 m², rund 50 Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Ca. 450 m², rund 50 Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-44-polski-sklep-kurpiak', 'shop'::public.place_kind, 52.4347083, 9.7219272, 'Hans-Böckler-Straße 8', '30851', 'Langenhagen', 'Niedersachsen', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep Kurpiak', 'Polski Sklep Kurpiak', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-kurpiak-16587127.html'),
('curated-xlsx-45-frischemarkt-sklep-polski-lueneburg', 'shop'::public.place_kind, 53.2461942, 10.4333966, 'Schützenstraße 98–99', '21337', 'Lüneburg', 'Niedersachsen', null, '{"raw": "Mo–Sa 07:00–20:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'FrischeMarkt – Sklep Polski Lüneburg', 'FrischeMarkt – Sklep Polski Lüneburg', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/frischemarkt---sklep-polski-lueneburg-13462559.html'),
('curated-xlsx-46-odra-deli', 'shop'::public.place_kind, 52.2947428, 8.0133276, 'Natruper Straße 230', '49090', 'Osnabrück', 'Niedersachsen', null, '{"raw": "Mo geschlossen; Di–Fr 10:00–18:30; Sa 09:00–15:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Odra Deli', 'Odra Deli', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-odra-deli-osnabrueck---polnischer-laden-odra-deli---osnabrueck-13487961.html'),
('curated-xlsx-47-beim-schlesier', 'shop'::public.place_kind, 50.8945947, 6.2823104, 'Kapellenplatz 12', '52457', 'Aldenhoven', 'Nordrhein-Westfalen', null, '{"raw": "Mo geschlossen; Di–Fr 10:00–18:00; Sa 09:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Beim Schlesier', 'Beim Schlesier', 'Polnische und schlesische Lebensmittel, Wurstwaren und Feinkost', 'Polnische und schlesische Lebensmittel, Wurstwaren und Feinkost', 'https://web2.cylex.de/firma-home/beim-schlesier--polski-sklep--polnisches-lebensmittel-10852472.html'),
('curated-xlsx-48-polonia-shop-bergheim', 'shop'::public.place_kind, 50.9458026, 6.6441119, 'Leipziger Straße 1/3', '50126', 'Bergheim', 'Nordrhein-Westfalen', 'https://polonia-shop.info/', '{"raw": "Mo–Sa 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polonia Shop Bergheim', 'Polonia Shop Bergheim', 'Ria-Geldtransfer; Versand nach Polen; barrierefrei; Kartenzahlung und Parkplätze Polnische Lebensmittel, Frischeprodukte, Getränke und Alltagswaren', 'Ria-Geldtransfer; Versand nach Polen; barrierefrei; Kartenzahlung und Parkplätze Polnische Lebensmittel, Frischeprodukte, Getränke und Alltagswaren', 'https://polonia-shop.info/');

insert into public.places (
  slug, kind, status, lat, lng, street, postal_code, city, state,
  website, phone, opening_hours, tags, source, source_url, verified_at
)
select slug, kind, 'published', lat, lng, street, postal_code, city, state,
  website, null, opening_hours, tags, 'curated'::public.place_source, source_url, now()
from tmp_curated
on conflict (slug) do update set
  kind = excluded.kind, status = 'published', lat = excluded.lat, lng = excluded.lng,
  street = excluded.street, postal_code = excluded.postal_code, city = excluded.city,
  state = excluded.state, website = excluded.website,
  opening_hours = excluded.opening_hours, tags = excluded.tags, source = excluded.source,
  source_url = excluded.source_url, verified_at = now(), updated_at = now();

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'de', s.name_de, s.desc_de, '', s.name_de || ' | Alemniam', left(s.desc_de, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'pl', s.name_pl, s.desc_pl, '', s.name_pl || ' | Alemniam', left(s.desc_pl, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;
commit;
