begin;
delete from public.places where source = 'curated';
create temporary table tmp_curated (
slug text primary key, kind public.place_kind, lat float8, lng float8,
street text, postal_code text, city text, state text, website text,
opening_hours jsonb, tags text[], name_de text, name_pl text,
desc_de text, desc_pl text, source_url text);
insert into tmp_curated values
('curated-xlsx-1-ropo-markt', 'shop'::public.place_kind, 48.754503, 8.5515762, 'Wilhelmstraße 89', '75323', 'Bad Wildbad', 'Baden-Württemberg', null, '{"raw": "Mo–Sa 09:00–19:00; So 10:00–18:00"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'RoPo Markt', 'RoPo Markt', 'Festes Geschäft mit rumänischem und polnischem Sortiment Polnische und rumänische Lebensmittel, Getränke, Süßwaren und Feinkost', 'Festes Geschäft mit rumänischem und polnischem Sortiment Polnische und rumänische Lebensmittel, Getränke, Süßwaren und Feinkost', 'https://web2.cylex.de/firma-home/ropo-markt--magazin-romanesc-polski-sklep--16789472.html'),
('curated-xlsx-2-lukullus-karlsruhe', 'shop'::public.place_kind, 49.0158964, 8.4225538, 'Klosterweg 10a', '76131', 'Karlsruhe', 'Baden-Württemberg', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Karlsruhe', 'Lukullus Karlsruhe', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 24.10.2019.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 24.10.2019.', 'https://lukullus-laden.eu/'),
('curated-xlsx-3-polskisklep-de-mannheim', 'shop'::public.place_kind, 49.5270941, 8.4875345, 'Hanauer Straße 25', '68305', 'Mannheim', 'Baden-Württemberg', 'https://polskisklep.de/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'PolskiSklep.de Mannheim', 'PolskiSklep.de Mannheim', 'Über 400 m²; Filiale seit 2017 Wurst, Fleisch, Milchprodukte, Fisch, Obst/Gemüse, Süßwaren, Konserven und Getränke Seit 2017.', 'Über 400 m²; Filiale seit 2017 Wurst, Fleisch, Milchprodukte, Fisch, Obst/Gemüse, Süßwaren, Konserven und Getränke Seit 2017.', 'https://polskisklep.de/'),
('curated-xlsx-4-polnische-spezialitaeten-grimm', 'shop'::public.place_kind, 48.7258147, 9.2725522, 'Herzog-Philipp-Platz 1', '73760', 'Ostfildern', 'Baden-Württemberg', 'https://www.polnische-spezialitäten-grimm.de/', '{"raw": "Mo–Mi 10:00–12:00 und 15:00–20:00; Do 09:00–14:00 und 15:00–20:00; Fr 09:00–20:00; Sa 09:00–18:00"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polnische Spezialitäten Grimm', 'Polnische Spezialitäten Grimm', 'Eingang über Robert-Koch-Straße; Paketversand nach Polen Polnische Spezialitäten und Lebensmittel', 'Eingang über Robert-Koch-Straße; Paketversand nach Polen Polnische Spezialitäten und Lebensmittel', 'https://www.polnische-spezialitäten-grimm.de/'),
('curated-xlsx-5-delicja-polnische-spezialitaeten', 'shop'::public.place_kind, 48.8909452, 8.6965215, 'Zerrennerstraße 26', '75172', 'Pforzheim', 'Baden-Württemberg', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Delicja Polnische Spezialitäten', 'Delicja Polnische Spezialitäten', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/delicja-polnische-spezialitaeten-16670359.html'),
('curated-xlsx-6-lukullus-stuttgart', 'shop'::public.place_kind, 48.8322935, 9.1865794, 'Erligheimer Straße 8', '70437', 'Stuttgart', 'Baden-Württemberg', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:30; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Stuttgart', 'Lukullus Stuttgart', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.10.2014.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.10.2014.', 'https://lukullus-laden.eu/'),
('curated-xlsx-7-lukullus-augsburg', 'shop'::public.place_kind, 48.3841506, 10.9214038, 'Klausstraße 24', '86167', 'Augsburg', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 10:00–20:00; Sa 10:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Augsburg', 'Lukullus Augsburg', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 19.03.2015.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 19.03.2015.', 'https://lukullus-laden.eu/'),
('curated-xlsx-8-lukullus-erlangen', 'shop'::public.place_kind, 49.5621721, 10.9616629, 'Sylvaniastraße 14', '91056', 'Erlangen', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Di 11:00–18:00; Mi–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Erlangen', 'Lukullus Erlangen', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.12.2021.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.12.2021.', 'https://lukullus-laden.eu/'),
('curated-xlsx-9-lukullus-landshut', 'shop'::public.place_kind, 48.5296389, 12.1461277, 'Innere Münchener Str. 18–20', '84036', 'Landshut', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Landshut', 'Lukullus Landshut', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 05.12.2019.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 05.12.2019.', 'https://lukullus-laden.eu/'),
('curated-xlsx-10-lukullus-muenchen-hadern', 'shop'::public.place_kind, 48.1193852, 11.483271, 'Guardinistraße 186', '81375', 'München', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus München-Hadern', 'Lukullus München-Hadern', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 18.07.2019.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 18.07.2019.', 'https://lukullus-laden.eu/'),
('curated-xlsx-11-lukullus-muenchen-hasenbergl', 'shop'::public.place_kind, 48.2074713, 11.552568, 'Rainfarnstraße 34', '80935', 'München', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–17:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus München-Hasenbergl', 'Lukullus München-Hasenbergl', 'Frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-12-ratibor-gabriela-s-polnische-spezialitaeten', 'shop'::public.place_kind, 49.4621674, 11.0224325, 'Fürther Straße 324', '90429', 'Nürnberg', 'Bayern', null, '{"raw": "Di–Fr 11:00–19:00; Sa 09:00–15:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Ratibor / Gabriela’s Polnische Spezialitäten', 'Ratibor / Gabriela’s Polnische Spezialitäten', 'Polnisch-schlesischer Spezialitätenladen Polnische und schlesische Lebensmittel, Getränke und Wurstwaren', 'Polnisch-schlesischer Spezialitätenladen Polnische und schlesische Lebensmittel, Getränke und Wurstwaren', 'https://www.google.com/search?q=Ratibor+Gabrielas+F%C3%BCrther+Stra%C3%9Fe+324+N%C3%BCrnberg'),
('curated-xlsx-13-lukullus-regensburg', 'shop'::public.place_kind, 49.0143786, 12.1180137, 'Greflinger Str. 53', '93055', 'Regensburg', 'Bayern', 'https://lukullus-laden.eu/', '{"raw": "Mo–Di 10:00–18:00; Mi–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Lukullus Regensburg', 'Lukullus Regensburg', 'Virtueller Rundgang; frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.11.2017.', 'Virtueller Rundgang; frische Lieferungen zweimal wöchentlich Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 16.11.2017.', 'https://lukullus-laden.eu/'),
('curated-xlsx-14-mini-center-shop-polnische-spezialitaeten', 'shop'::public.place_kind, 49.0076198, 13.2485938, 'Flanitzer Straße 20', '94227', 'Zwiesel', 'Bayern', 'https://minicentershop.de/', '{"raw": "Mo–Fr 10:00–19:00; Sa 09:00–14:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Mini Center Shop + Polnische Spezialitäten', 'Mini Center Shop + Polnische Spezialitäten', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://minicentershop.de/'),
('curated-xlsx-15-feinkost-bogocz-bistro-n-13', 'shop'::public.place_kind, 52.4161293, 13.4044131, 'Schlierbacher Weg 7–9', '12349', 'Berlin', 'Berlin', 'https://www.feinkost-bogocz.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Bogocz + Bistro N°13', 'Feinkost Bogocz + Bistro N°13', 'Feinkost, Catering, Plattenservice und polnischer Mittagstisch Polnische Feinkost, Wurst/Fleisch, warme Gerichte und Partyservice', 'Feinkost, Catering, Plattenservice und polnischer Mittagstisch Polnische Feinkost, Wurst/Fleisch, warme Gerichte und Partyservice', 'https://www.feinkost-bogocz.de/'),
('curated-xlsx-16-feinkost-haeusler-reinickendorf', 'shop'::public.place_kind, 52.567222, 13.362193, 'Residenzstraße 34', '13409', 'Berlin', 'Berlin', 'https://polskashop.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Häusler Reinickendorf', 'Feinkost Häusler Reinickendorf', 'In den Resi-Passagen Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'In den Resi-Passagen Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'https://polskashop.de/'),
('curated-xlsx-17-feinkost-haeusler-schoeneberg', 'shop'::public.place_kind, 52.5037904, 13.3445812, 'Bayreuther Straße 44', '10787', 'Berlin', 'Berlin', 'https://polskashop.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Häusler Schöneberg', 'Feinkost Häusler Schöneberg', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'https://polskashop.de/'),
('curated-xlsx-18-feinkost-haeusler-steglitz', 'shop'::public.place_kind, 52.455502, 13.3259094, 'Albrechtstraße 120', '12169', 'Berlin', 'Berlin', 'https://polskashop.de/', '{"raw": "Mo–Fr 09:00–18:00; Sa 09:00–14:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Feinkost Häusler Steglitz', 'Feinkost Häusler Steglitz', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'Polnisch-schlesische Feinkost Polnische und schlesische Lebensmittel, Wurst/Schinken, Süßwaren, Milchprodukte, Mehlwaren; frisches polnisches Brot Mo/Mi/Fr', 'https://polskashop.de/'),
('curated-xlsx-19-maly-ksiaze', 'shop'::public.place_kind, 52.4880745, 13.4075661, 'Lilienthalstraße 6', '10965', 'Berlin', 'Berlin', 'https://polnische-lebensmittel.berlin/', '{"raw": "Mo–Sa 10:00–20:00; So 10:00–20:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Mały Książę', 'Mały Książę', 'Laden und Café; DHL-Paketshop Pierogi, Suppen, Kuchen, Pfannkuchen, Wurst/Käse, Backwaren, Getränke und Spirituosen Seit seit ca. 2014.', 'Laden und Café; DHL-Paketshop Pierogi, Suppen, Kuchen, Pfannkuchen, Wurst/Käse, Backwaren, Getränke und Spirituosen Seit seit ca. 2014.', 'https://polnische-lebensmittel.berlin/'),
('curated-xlsx-20-polski-sklep-dosia', 'shop'::public.place_kind, 52.4254275, 13.4630198, 'Lipschitzallee 68', '12353', 'Berlin', 'Berlin', null, '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–14:00; So 10:00–12:30"}'::jsonb, array['xlsx','feste-standorte','fachmarkt']::text[], 'Polski Sklep DOSIA', 'Polski Sklep DOSIA', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-dosia-13284424.html'),
('curated-xlsx-21-u-zosi-spandau', 'shop'::public.place_kind, 52.536032, 13.2039749, 'Breite Straße 63', '13597', 'Berlin', 'Berlin', 'https://www.instagram.com/u_zosi_berlin/', '{"raw": "Mo–Fr 09:00–20:00; Sa 10:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'U Zosi – Spandau', 'U Zosi – Spandau', 'Zweite Berliner Filiale laut Social-Media-Profil Polnische Lebensmittel und Spezialitäten', 'Zweite Berliner Filiale laut Social-Media-Profil Polnische Lebensmittel und Spezialitäten', 'https://www.instagram.com/u_zosi_berlin/'),
('curated-xlsx-22-u-zosi-turmstrasse', 'shop'::public.place_kind, 52.5264816, 13.3506918, 'Turmstraße 13', '10559', 'Berlin', 'Berlin', 'https://www.instagram.com/u_zosi_berlin/', '{"raw": "Mo–Fr 08:00–21:00; Sa 09:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte']::text[], 'U Zosi – Turmstraße', 'U Zosi – Turmstraße', 'Polnischer Nachbarschaftsladen; bereits 2009 erwähnt Polnische Lebensmittel und Spezialitäten Seit seit 2009 oder früher.', 'Polnischer Nachbarschaftsladen; bereits 2009 erwähnt Polnische Lebensmittel und Spezialitäten Seit seit 2009 oder früher.', 'https://www.instagram.com/u_zosi_berlin/'),
('curated-xlsx-23-polnische-feinkost-cottbus', 'shop'::public.place_kind, 51.7632033, 14.346869, 'Hermannstraße 12', '03042', 'Cottbus', 'Brandenburg', 'https://polnische-feinkost-cottbus.de/', '{"raw": "Mo 09:00–18:00; Di 09:00–14:00; Mi 09:00–18:00; Do 09:00–14:00; Fr 09:00–13:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'Polnische Feinkost Cottbus', 'Polnische Feinkost Cottbus', 'Kleiner polnischer Feinkostladen Polnische Lebensmittel und Feinkost', 'Kleiner polnischer Feinkostladen Polnische Lebensmittel und Feinkost', 'https://polnische-feinkost-cottbus.de/'),
('curated-xlsx-24-gucio-polnische-spezialitaeten', 'shop'::public.place_kind, 53.0863872, 8.8894697, 'August-Bebel-Allee 298', '28329', 'Bremen', 'Bremen', 'https://gucio.de/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte']::text[], 'GUCIO Polnische Spezialitäten', 'GUCIO Polnische Spezialitäten', 'Polnischer Spezialitätenmarkt Wurstwaren, polnische Lebensmittel sowie saisonales Obst und Gemüse', 'Polnischer Spezialitätenmarkt Wurstwaren, polnische Lebensmittel sowie saisonales Obst und Gemüse', 'https://gucio.de/');

insert into public.places (
  slug, kind, status, lat, lng, street, postal_code, city, state,
  website, phone, opening_hours, tags, source, source_url, verified_at
)
select slug, kind, 'published', lat, lng, street, postal_code, city, state,
  website, null, opening_hours, tags, 'curated'::public.place_source, source_url, now()
from tmp_curated
on conflict (slug) do update set
  kind = excluded.kind, status = 'published', lat = excluded.lat, lng = excluded.lng,
  street = excluded.street, postal_code = excluded.postal_code, city = excluded.city,
  state = excluded.state, website = excluded.website,
  opening_hours = excluded.opening_hours, tags = excluded.tags, source = excluded.source,
  source_url = excluded.source_url, verified_at = now(), updated_at = now();

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'de', s.name_de, s.desc_de, '', s.name_de || ' | Alemniam', left(s.desc_de, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'pl', s.name_pl, s.desc_pl, '', s.name_pl || ' | Alemniam', left(s.desc_pl, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;
commit;
