begin;
create temporary table tmp_curated (
slug text primary key, kind public.place_kind, lat float8, lng float8,
street text, postal_code text, city text, state text, website text,
opening_hours jsonb, tags text[], name_de text, name_pl text,
desc_de text, desc_pl text, source_url text);
insert into tmp_curated values
('curated-xlsx-49-lukullus-bielefeld', 'shop'::public.place_kind, 52.0245805, 8.5650171, 'Lohbreite 1', '33607', 'Bielefeld', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Di–Fr 10:00–18:00; Sa 09:00–15:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Lukullus Bielefeld', 'Lukullus Bielefeld', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 31.05.2012.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 31.05.2012.', 'https://lukullus-laden.eu/'),
('curated-xlsx-50-polonia-market-bonn', 'market'::public.place_kind, 50.7537013, 7.0730404, 'Kölnstraße 464', '53117', 'Bonn', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte','market','polenladen-polnischer-fachmarkt']::text[], 'Polonia Market Bonn', 'Polonia Market Bonn', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-51-polski-sklep-polka', 'market'::public.place_kind, 50.8194392, 6.8925277, 'Römerstraße 1', '50321', 'Brühl', 'Nordrhein-Westfalen', null, '{"raw": "Mo–Sa 08:30–20:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','market','polnischer-lebensmittelmarkt']::text[], 'Polski Sklep Polka', 'Polski Sklep Polka', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-polka-13758628.html'),
('curated-xlsx-52-polski-sklep-dormagen', 'market'::public.place_kind, 51.0919782, 6.8431939, 'Kölner Straße 55', '41539', 'Dormagen', 'Nordrhein-Westfalen', 'https://www.polskisklep-dormagen.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 09:00–16:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','market','polnischer-lebensmittelmarkt']::text[], 'Polski Sklep Dormagen', 'Polski Sklep Dormagen', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://www.polskisklep-dormagen.de/'),
('curated-xlsx-53-golly-s-dortmund-brackel', 'shop'::public.place_kind, 51.5225888, 7.5552772, 'Holzwickeder Str. 45', '44309', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-brackel-holzwickeder-str-45/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Golly’s Dortmund-Brackel', 'Golly’s Dortmund-Brackel', 'Kartenzahlung; Beratung; Frischetheke Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'Kartenzahlung; Beratung; Frischetheke Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'https://www.gollys.de/store/fachgeschaeft-dortmund-brackel-holzwickeder-str-45/'),
('curated-xlsx-54-golly-s-dortmund-scharnhorst', 'shop'::public.place_kind, 51.5577832, 7.5449732, 'Droote 56', '44328', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-droote-56/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Golly’s Dortmund-Scharnhorst', 'Golly’s Dortmund-Scharnhorst', 'Mittagstisch; seit 1996 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 1996.', 'Mittagstisch; seit 1996 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 1996.', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-droote-56/'),
('curated-xlsx-55-golly-s-dortmund-scharnhorst-eks', 'shop'::public.place_kind, 51.5520215, 7.54369, 'Gleiwitzstraße 271', '44328', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-eks-gleiwitzstrasse-271/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Golly’s Dortmund-Scharnhorst-EKS', 'Golly’s Dortmund-Scharnhorst-EKS', 'Im Einkaufszentrum Scharnhorst-EKS Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'Im Einkaufszentrum Scharnhorst-EKS Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven', 'https://www.gollys.de/store/fachgeschaeft-dortmund-scharnhorst-eks-gleiwitzstrasse-271/'),
('curated-xlsx-56-golly-s-dortmund-wickede', 'shop'::public.place_kind, 51.5323672, 7.6106967, 'Wickeder Hellweg 90', '44319', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.gollys.de/store/fachgeschaeft-dortmund-wickede-wickeder-hellweg-90/', '{"raw": "Di–Fr 08:00–18:00; Sa 08:00–13:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Golly’s Dortmund-Wickede', 'Golly’s Dortmund-Wickede', 'Nahe U-Bahn; seit 2014 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 2014.', 'Nahe U-Bahn; seit 2014 an diesem Standort Eigene schlesische/polnische Fleischerei: Wurst, Schinken und Frischfleisch; dazu Pierogi, Käse, Backwaren, Süßwaren, Getränke und Konserven Seit 2014.', 'https://www.gollys.de/store/fachgeschaeft-dortmund-wickede-wickeder-hellweg-90/'),
('curated-xlsx-57-lukullus-dortmund-unna', 'shop'::public.place_kind, 51.5358516, 7.6119783, 'Wickeder Straße 35', '44319', 'Dortmund', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Lukullus Dortmund-Unna', 'Lukullus Dortmund-Unna', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 11.06.2012.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 11.06.2012.', 'https://lukullus-laden.eu/'),
('curated-xlsx-58-promo-polski-supermarket-dortmund', 'shop'::public.place_kind, 51.515648, 7.5041094, 'Körner Hellweg 47–49', '44143', 'Dortmund', 'Nordrhein-Westfalen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Promo Polski Supermarket Dortmund', 'Promo Polski Supermarket Dortmund', 'Große Getränkeauswahl Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Große Getränkeauswahl Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-59-promo-polski-supermarket-duisburg', 'shop'::public.place_kind, 51.4970582, 6.7986999, 'Hohenzollernplatz 16', '47167', 'Duisburg', 'Nordrhein-Westfalen', 'https://www.promo-supermarkt.de/', '{"raw": "Mo–So 08:00–20:00"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Promo Polski Supermarket Duisburg', 'Promo Polski Supermarket Duisburg', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'Viele Parkmöglichkeiten Polnische Traditionswaren, Backwaren, Fleisch/Wurst, Getränke, Süßwaren, Kühl- und Tiefkühlprodukte', 'https://www.promo-supermarkt.de/'),
('curated-xlsx-60-viktualia', 'shop'::public.place_kind, 51.4321668, 6.7632945, 'Wallstraße 8', '47051', 'Duisburg', 'Nordrhein-Westfalen', 'https://www.viktualia.eu/', '{"raw": "Mo–Fr 10:00–18:00; Sa 09:00–15:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polnisch-schlesischer-feinkostla']::text[], 'Viktualia', 'Viktualia', 'Deutsch- und polnischsprachiges Team Polnische und schlesische Delikatessen, Wurst, Fleisch, Süßwaren und Feinkost Seit 2010.', 'Deutsch- und polnischsprachiges Team Polnische und schlesische Delikatessen, Wurst, Fleisch, Süßwaren und Feinkost Seit 2010.', 'https://www.viktualia.eu/'),
('curated-xlsx-61-lukullus-duesseldorf-garath', 'shop'::public.place_kind, 51.1430231, 6.8958276, 'Kurt-Schumacher-Str. 2', '40595', 'Düsseldorf', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Lukullus Düsseldorf-Garath', 'Lukullus Düsseldorf-Garath', 'Kostenlose Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 04.04.2009.', 'Kostenlose Parkplätze Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 04.04.2009.', 'https://lukullus-laden.eu/'),
('curated-xlsx-62-polonia-market-essen-frohnhausen', 'market'::public.place_kind, 51.4494145, 6.9711551, 'Frohnhauser Str. 282', '45144', 'Essen', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 08:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte','market','polenladen-polnischer-fachmarkt']::text[], 'Polonia Market Essen-Frohnhausen', 'Polonia Market Essen-Frohnhausen', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-63-polonia-market-essen-steele', 'market'::public.place_kind, 51.4464148, 7.0502636, 'Steeler Str. 339', '45138', 'Essen', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte','market','polenladen-polnischer-fachmarkt']::text[], 'Polonia Market Essen-Steele', 'Polonia Market Essen-Steele', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-64-polonia-market-euskirchen', 'market'::public.place_kind, 50.6665117, 6.7839524, 'Charleviller Platz 29', '53879', 'Euskirchen', 'Nordrhein-Westfalen', 'https://poloniamarket.de/', '{"raw": "Mo–Fr 09:00–20:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte','market','polenladen-polnischer-fachmarkt']::text[], 'Polonia Market Euskirchen', 'Polonia Market Euskirchen', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'Parkplätze vorhanden Polnische Lebensmittel und Feinkost, frische Waren, Wurst/Fleisch, Süßwaren, Getränke und haltbare Spezialitäten', 'https://poloniamarket.de/'),
('curated-xlsx-65-lukullus-gelsenkirchen-beckhausen', 'shop'::public.place_kind, 51.5519731, 7.0442822, 'Horster Str. 350', '45899', 'Gelsenkirchen', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 10:00–17:00; Sa 10:00–14:00"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Lukullus Gelsenkirchen-Beckhausen', 'Lukullus Gelsenkirchen-Beckhausen', 'Kostenlose Parkplätze gegenüber; Restaurant Janosik nebenan Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'Kostenlose Parkplätze gegenüber; Restaurant Janosik nebenan Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol', 'https://lukullus-laden.eu/'),
('curated-xlsx-66-nasza-pszcz-lka', 'market'::public.place_kind, 51.5200248, 7.1252872, 'Neuhüller Straße 38', '45888', 'Gelsenkirchen', 'Nordrhein-Westfalen', 'https://sellwerk.de/firmenprofil/nasza-pszczolka', '{"raw": "Mo–Sa 08:00–21:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','market','polnischer-lebensmittelmarkt']::text[], 'Nasza Pszczółka', 'Nasza Pszczółka', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Großzügige Öffnungszeiten Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://sellwerk.de/firmenprofil/nasza-pszczolka'),
('curated-xlsx-67-lukullus-hagen-gevelsberg', 'shop'::public.place_kind, 51.3357654, 7.3825391, 'Hagener Str. 360', '58285', 'Gevelsberg', 'Nordrhein-Westfalen', 'https://lukullus-laden.eu/', '{"raw": "Mo–Fr 09:00–19:00; Sa 09:00–16:00"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Lukullus Hagen-Gevelsberg', 'Lukullus Hagen-Gevelsberg', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 06.12.2018.', 'Polnische Wurst- und Fleischwaren, Käse/Milchprodukte, Süßwaren, Getränke, Konserven, Teigwaren; je nach Filiale Presse, Kosmetik und Alkohol Seit 06.12.2018.', 'https://lukullus-laden.eu/'),
('curated-xlsx-68-pol-markt-hagen', 'shop'::public.place_kind, 51.3801852, 7.477946, 'Boeler Straße 124', '58097', 'Hagen', 'Nordrhein-Westfalen', 'https://pol-markt.com/', '{"raw": "Mo–Fr 08:00–19:00; Sa 08:00–18:00"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'POL-MARKT Hagen', 'POL-MARKT Hagen', 'Großer polnischer Supermarkt Polnische/schlesische Wurst und Schinken, Gemüse, Kuchen, Gewürze, Süßwaren, Kosmetik und Haushaltswaren', 'Großer polnischer Supermarkt Polnische/schlesische Wurst und Schinken, Gemüse, Kuchen, Gewürze, Süßwaren, Kosmetik und Haushaltswaren', 'https://pol-markt.com/'),
('curated-xlsx-69-pola-market', 'market'::public.place_kind, 51.7311982, 6.5897486, 'Marktstraße 19B', '46499', 'Hamminkeln', 'Nordrhein-Westfalen', 'https://polamarket.de/', '{"raw": "Mo 10:00–19:00; Di 10:00–19:00; Mi–Fr 09:00–19:00; Sa 10:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','market','polnischer-lebensmittelmarkt']::text[], 'Pola Market', 'Pola Market', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://polamarket.de/'),
('curated-xlsx-70-polski-sklep-herford', 'market'::public.place_kind, 52.1301128, 8.6985354, 'Amselplatz 1', '32049', 'Herford', 'Nordrhein-Westfalen', null, '{"raw": "Mo–Sa 08:00–18:00; So geschlossen"}'::jsonb, array['xlsx','feste-standorte','market','polnischer-lebensmittelmarkt']::text[], 'Polski Sklep Herford', 'Polski Sklep Herford', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'Polnische Lebensmittel; je nach Geschäft Wurst und Fleisch, Käse und Milchprodukte, Backwaren, Pierogi/Tiefkühlware, Süßwaren, Getränke, Konserven und Haushaltswaren', 'https://web2.cylex.de/firma-home/polski-sklep-13195564.html'),
('curated-xlsx-71-anna-polnische-spezialitaeten', 'shop'::public.place_kind, 51.1807429, 6.9206953, 'Herderstraße 94', '40721', 'Hilden', 'Nordrhein-Westfalen', 'https://www.anzeiger24.de/hilden/Anna-Polnische-Spezialitaeten-Supermarkt', '{"raw": "Di–Fr 09:00–18:00; Sa 09:00–13:00; Mo laut Quelle geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Anna – Polnische Spezialitäten', 'Anna – Polnische Spezialitäten', 'Frischetheke; neuer Markt seit Sommer 2025 Pierogi, Wurst/Fleisch, Obst/Gemüse, Kuchen, Süßwaren, Getränke, Konserven, Gewürze und Saucen Seit Sommer 2025.', 'Frischetheke; neuer Markt seit Sommer 2025 Pierogi, Wurst/Fleisch, Obst/Gemüse, Kuchen, Süßwaren, Getränke, Konserven, Gewürze und Saucen Seit Sommer 2025.', 'https://www.anzeiger24.de/hilden/Anna-Polnische-Spezialitaeten-Supermarkt'),
('curated-xlsx-72-sklep-lasota-ham', 'shop'::public.place_kind, 51.3973312, 7.6936548, 'Giesestraße 3', '58636', 'Iserlohn', 'Nordrhein-Westfalen', 'https://lasotaham.de/', '{"raw": "Di–Fr 10:00–18:00; Sa 09:00–16:00; Mo geschlossen"}'::jsonb, array['xlsx','feste-standorte','shop','polenladen-polnischer-fachmarkt']::text[], 'Sklep Lasota HAM', 'Sklep Lasota HAM', 'Polnischer Spezialitätenladen Polnische Lebensmittel und Feinkost', 'Polnischer Spezialitätenladen Polnische Lebensmittel und Feinkost', 'https://lasotaham.de/');

insert into public.places (
  slug, kind, status, lat, lng, street, postal_code, city, state,
  website, phone, opening_hours, tags, source, source_url, verified_at
)
select slug, kind, 'published', lat, lng, street, postal_code, city, state,
  website, null, opening_hours, tags, 'curated'::public.place_source, source_url, now()
from tmp_curated
on conflict (slug) do update set
  kind = excluded.kind, status = 'published', lat = excluded.lat, lng = excluded.lng,
  street = excluded.street, postal_code = excluded.postal_code, city = excluded.city,
  state = excluded.state, website = excluded.website,
  opening_hours = excluded.opening_hours, tags = excluded.tags, source = excluded.source,
  source_url = excluded.source_url, verified_at = now(), updated_at = now();

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'de', s.name_de, s.desc_de, '', s.name_de || ' | Alemniam', left(s.desc_de, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'pl', s.name_pl, s.desc_pl, '', s.name_pl || ' | Alemniam', left(s.desc_pl, 155)
from tmp_curated s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;
commit;
