#!/usr/bin/env python3
"""Fast OSM place refresh via Photon (Komoot) + Overpass detail tags.

Legal: OpenStreetMap data © OSM contributors, ODbL.
Usage: python3 scripts/import-osm-places.py > /tmp/osm_places.sql
Then run the SQL in Supabase (service role / SQL editor).
"""

from __future__ import annotations

import json
import re
import time
import urllib.parse
import urllib.request
from collections import Counter

UA = "AlemniamPlaceImport/1.0 (OSM ODbL; https://github.com/Eventversicherung/rezeptePL)"
PHOTON = "https://photon.komoot.io/api/"
OVERPASS = "https://overpass.openstreetmap.fr/api/interpreter"

QUERIES = [
    "Polski Sklep",
    "Sklep Polski",
    "Polonia Market",
    "Polenmarkt",
    "Delikatesy",
    "Polnische Delikatessen",
]


def fetch_photon(q: str) -> list[dict]:
    url = f"{PHOTON}?q={urllib.parse.quote(q)}&bbox=5.8,47.2,15.1,55.1&limit=50&lang=de"
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode()).get("features", [])


def esc(s: str | None) -> str:
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def main() -> None:
    merged: dict = {}
    for q in QUERIES:
        for f in fetch_photon(q):
            props = f.get("properties") or {}
            coords = (f.get("geometry") or {}).get("coordinates") or []
            if len(coords) < 2:
                continue
            lon, lat = coords[0], coords[1]
            if not (47.2 <= lat <= 55.1 and 5.8 <= lon <= 15.1):
                continue
            name = props.get("name")
            if not name:
                continue
            nl = name.lower()
            if not re.search(
                r"polsk|polonia|polenmarkt|polnisch|delikatesy\b|mini\s*europa",
                nl,
            ):
                continue
            k = props.get("osm_key")
            if k in ("highway", "place", "office", "landuse", "building", "man_made"):
                continue
            key = (props.get("osm_type"), props.get("osm_id"))
            if not key[1]:
                continue
            merged[key] = {
                "name": name,
                "lat": lat,
                "lng": lon,
                "city": props.get("city")
                or props.get("town")
                or props.get("village")
                or "",
                "state": props.get("state") or "",
                "street": " ".join(
                    x for x in [props.get("street"), props.get("housenumber")] if x
                ),
                "postal_code": props.get("postcode") or "",
                "osm_type": props.get("osm_type"),
                "osm_id": props.get("osm_id"),
                "osm_key": k,
                "osm_value": props.get("osm_value"),
            }
        time.sleep(1.0)

    nodes = [str(v["osm_id"]) for v in merged.values() if v["osm_type"] == "N"]
    ways = [str(v["osm_id"]) for v in merged.values() if v["osm_type"] == "W"]
    parts = []
    if nodes:
        parts.append(f"node(id:{','.join(nodes)});")
    if ways:
        parts.append(f"way(id:{','.join(ways)});")
    q = "[out:json][timeout:60];(" + "".join(parts) + ");out center tags;"
    req = urllib.request.Request(
        OVERPASS,
        data=urllib.parse.urlencode({"data": q}).encode(),
        headers={
            "User-Agent": UA,
            "Content-Type": "application/x-www-form-urlencoded",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=70) as r:
        detail = json.loads(r.read().decode())
    by = {}
    for e in detail.get("elements", []):
        tmap = {"node": "N", "way": "W", "relation": "R"}
        by[(tmap.get(e.get("type")), e.get("id"))] = e

    print("-- OSM import generated by scripts/import-osm-places.py")
    print("begin;")
    print("delete from public.places where source in ('curated', 'osm');")
    print(
        "create temporary table tmp_osm ("
        "slug text primary key, kind public.place_kind, lat float8, lng float8, "
        "street text, postal_code text, city text, state text, website text, phone text, "
        "opening_hours jsonb, tags text[], name_de text, name_pl text, "
        "desc_de text, desc_pl text, source_url text);"
    )
    vals = []
    for f in merged.values():
        e = by.get((f["osm_type"], f["osm_id"]))
        tags = (e or {}).get("tags") or {}
        website = tags.get("website") or tags.get("contact:website") or tags.get("url")
        phone = tags.get("phone") or tags.get("contact:phone")
        opening = tags.get("opening_hours") or ""
        name = f["name"]
        kind = (
            "market"
            if tags.get("amenity") == "marketplace" or "polenmarkt" in name.lower()
            else "shop"
        )
        lat, lng = f["lat"], f["lng"]
        if e:
            if "lat" in e:
                lat, lng = e["lat"], e["lon"]
            elif "center" in e:
                lat, lng = e["center"]["lat"], e["center"]["lon"]
        street = f["street"] or " ".join(
            x for x in [tags.get("addr:street"), tags.get("addr:housenumber")] if x
        )
        city = f["city"] or tags.get("addr:city") or "Deutschland"
        postal = f["postal_code"] or tags.get("addr:postcode") or ""
        state = f["state"] or ""
        slug_base = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:40] or "place"
        slug = f"osm-{f['osm_type'].lower()}-{f['osm_id']}-{slug_base}"[:80]
        ot = {"N": "node", "W": "way", "R": "relation"}.get(f["osm_type"], "node")
        source_url = f"https://www.openstreetmap.org/{ot}/{f['osm_id']}"
        oh = json.dumps({"raw": opening} if opening else {}, ensure_ascii=False)
        tag_arr = "array[" + ",".join(
            esc(t) for t in [tags.get("shop") or tags.get("amenity"), "osm"] if t
        ) + "]::text[]"
        vals.append(
            "("
            f"{esc(slug)}, '{kind}'::public.place_kind, {lat}, {lng}, "
            f"{esc(street)}, {esc(postal)}, {esc(city)}, {esc(state)}, "
            f"{esc(website) if website else 'null'}, {esc(phone) if phone else 'null'}, "
            f"{esc(oh)}::jsonb, {tag_arr}, {esc(name)}, {esc(name)}, "
            f"{esc('Öffentlicher Eintrag aus OpenStreetMap.')}, "
            f"{esc('Publiczny wpis z OpenStreetMap.')}, {esc(source_url)}"
            ")"
        )
    print("insert into tmp_osm values\n" + ",\n".join(vals) + ";")
    print(
        """
insert into public.places (
  slug, kind, status, lat, lng, street, postal_code, city, state,
  website, phone, opening_hours, tags, source, source_url, verified_at
)
select slug, kind, 'published', lat, lng, street, postal_code, city, state,
  website, phone, opening_hours, tags, 'osm'::public.place_source, source_url, now()
from tmp_osm
on conflict (slug) do update set
  kind = excluded.kind, status = 'published', lat = excluded.lat, lng = excluded.lng,
  street = excluded.street, postal_code = excluded.postal_code, city = excluded.city,
  state = excluded.state, website = excluded.website, phone = excluded.phone,
  opening_hours = excluded.opening_hours, tags = excluded.tags, source = excluded.source,
  source_url = excluded.source_url, verified_at = now(), updated_at = now();

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'de', s.name_de, s.desc_de, '', s.name_de || ' | Alemniam', left(s.desc_de, 155)
from tmp_osm s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;

insert into public.place_translations (place_id, locale, name, description, schedule_note, seo_title, seo_description)
select p.id, 'pl', s.name_pl, s.desc_pl, '', s.name_pl || ' | Alemniam', left(s.desc_pl, 155)
from tmp_osm s join public.places p on p.slug = s.slug
on conflict (place_id, locale) do update set
  name = excluded.name, description = excluded.description,
  seo_title = excluded.seo_title, seo_description = excluded.seo_description;
commit;
"""
    )
    print(f"-- imported candidates: {len(vals)}", file=__import__("sys").stderr)
    print(f"-- types: {Counter()}", file=__import__("sys").stderr)


if __name__ == "__main__":
    main()
