-- AUTO-GENERATED by scripts/generate-supabase-import.ts — do not edit by hand.
-- Regenerate after any seed*.ts content change: npx tsx scripts/generate-supabase-import.ts
begin;

-- blog:post-kiszenie
insert into public.blog_posts (id, status, post_type, cover_image, silo_ids, related_recipe_ids, related_post_ids, related_product_ids, cluster_ids, published_at, updated_at) values ('post-kiszenie', 'published', 'guide', 'https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/blog/post-kiszenie/bbd62ba7-3d38-461a-a524-82923fa60a2c.webp', array['technique']::text[], array['recipe-bigos', 'recipe-pierogi-cabbage', 'recipe-barszcz', 'recipe-ogorkowa', 'recipe-kapusniak', 'recipe-kapusta-zasmażana', 'recipe-ogorki-kiszone', 'recipe-kapusta-kiszona', 'recipe-czosnek-kiszony']::text[], array['post-bigos-guide', 'post-zakwas-zurek', 'post-polenladen', 'post-ferment-glaeser']::text[], '{}'::text[], array['technique-kiszenie']::text[], '2026-07-24T09:00:00.000Z', '2026-07-24T09:00:00.000Z') on conflict (id) do update set status = excluded.status, post_type = excluded.post_type, cover_image = excluded.cover_image, silo_ids = excluded.silo_ids, related_recipe_ids = excluded.related_recipe_ids, related_post_ids = excluded.related_post_ids, related_product_ids = excluded.related_product_ids, cluster_ids = excluded.cluster_ids, published_at = excluded.published_at, updated_at = excluded.updated_at;
insert into public.blog_post_translations (post_id, locale, title, slug, excerpt, body, seo_title, seo_description) values ('post-kiszenie', 'de', 'Kiszenie zu Hause: Kapusta, Ogórki, saubere Technik', 'kiszenie-guide', 'Fermentieren im deutschen Haushalt: Salz, Temperatur, Gläser, Sicherheit — und was wir für Bigos selbst machen.', 'Kiszenie ist kontrollierte Milchsäuregärung – keine Essig-Abkürzung. Sauberes Arbeiten, frisches Gemüse, Salz, passendes Gefäß. Gurken, Kohl, Rote Bete für Alltag und [Barszcz](/de/rezepte/barszcz-czerwony). Orientierung: [bzfe.de](https://www.bzfe.de), [ncez.pzh.gov.pl](https://ncez.pzh.gov.pl), [agriculture.ec.europa.eu](https://agriculture.ec.europa.eu), [was-wir-essen.de](https://www.was-wir-essen.de). Sicherheit zuerst.

## Grundidee

Milchsäurebakterien säuern unter der Lake. Luftkontakt und Schmutz sind Feinde. Essig ergibt anderes Produkt.



![Gericht aus der polnischen Küche](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-ogorkowa/fe6aee59-9d09-475d-8464-4012dab7203a.webp)

## Starter-Setup

Sauberes Glas/Gefäß, Gewicht zum Unter-Lake-Halten, geeignetes Salz, frisches unbeschädigtes Gemüse, Rezept mit Salzmenge – nicht raten.

## Gurken

Fest, ungewachst bevorzugt, Gewürze nach Hausbrauch (Dill, Knoblauch, Meerrettich, Pfeffer). Lake bedeckt alles.

## Kohl

Fein schneiden, mit Salz massieren, fest einstampfen, Lake/Saft bedeckt. Zeit und Temperatur beobachten.

## Rote Bete

Für klare säuerliche Noten; Hände/Flächen schützen vor Farbe. Zu [Barszcz](/de/rezepte/barszcz-czerwony) und kalten Speisen.

## Temperatur

Raumwarm zum Start der Gärung, später kühlen. Zu warm = unkontrolliert; zu kalt = träge.

## Beobachten

Bläschen/säuerlicher Duft normal. Flaumschimmel, Fäulnis, Extreme Farben: vollständig entsorgen, nicht „abschöpfen und hoffen“.

## Lagerung

Nach gewünschter Säure kühl. Sauberer Entnahmelöffel. Kleine Chargen zum Lernen.

## Hygiene

Hände, Gläser, keine beschädigten Deckel die nicht entlüften können wenn nötig. bzfe.de-Mindset.



![Zubereitung in der Diaspora-Küche](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-kapusniak/d602b625-35e3-4b65-88c1-1202fd7d9507.webp)

## Küche DE

Gemüse aus Supermarkt oft ok; Qualität prüfen. Speisesalz ohne unerwünschte Zusätze laut Rezept wählen.

## Fehler

Zu wenig Salz; Gemüse schaut raus; schmutziges Glas; Zuwachs mit Essig verwechseln; große Erstcharge.

## Nutzung

Zu [Sonntagsessen](/de/blog/sonntagsessen-polnisch), zu Pierogi-Tellern, in Salaten. Kiszone Gurken wandern in [Ogórkowa](/de/rezepte/ogorkowa); Kapusta kiszona in [Kapuśniak](/de/rezepte/kapusniak), warme Beilage [Kapusta zasmażana](/de/rezepte/kapusta-zasmażana) oder Bigos — Säure dosieren.

## Verwandt Zakwas

Andere Zutat, ähnliche Sorgfalt – [Zakwas](/de/blog/zakwas-zurek).

## Dokumentation

Datum, Salz%, Raumtemp, Tag der Kühlung notieren.

## FAQ

### Essig statt Ferment?

Ergibt Essiggurken/-kraut, nicht klassisches Kiszenie. Mag ok schmecken, ist aber anderes. Für Lernerfolg Fermentregeln einhalten oder bewusst Essigprodukt wählen und so nennen.

### Welches Salz?

Rezept folgen; oft unjodiert/ohne Antiklumpmittel bevorzugt in Fermentkreisen – Herstellerangaben und erprobte Rezepte nutzen statt Internetmythen. Menge genau wiegen.

### Schimmel – retten?

Nein bei Unsicherheit. Vollständig entsorgen, Gefäß reinigen, neu starten. Gesundheit geht vor. Besonders bei weichem Gemüse und Raumwärme streng sein.

### Wie lange fermentieren?

Bis gewünschte Säure; Temperaturabhängig. Kosten und riechen. Dann kühlen. Kalender allein reicht nicht. Kleine Charge lehrt Tempo eures Zuhauses.

### Kinder & Immunschwache?

Vorsicht mit Hausfermenten; ggf. zuverlässige Kaufprodukte. Im Zweifel fachlich informieren und risikoarm wählen. bzfe.de/ncez als Rahmen.

### Welches Gefäß?

Lebensmittelgeeignetes Glas bewährt. Beschädigte Deckel meiden. Gasentwicklung bedenken. Zu große Fässer erst nach Erfahrung.

## Kiszenie und Wochenmenü

Ein Glas Gurken oder Kraut macht einfache Kartoffel- und Pierogiteller spannender ohne zweiten Topf. Vorrat ist Geschmacksinfrastruktur.

## Wenn es zu sauer wird

Mit milden Beilagen ausgleichen, in Saucen dosieren, oder als Würzkomponente statt Hauptbeilage. Nächste Charge früher kühlen.', 'Kiszenie zu Hause | Fermentieren Guide | Alemniam', 'Kiszenie Guide: Kapusta und Ogórki zu Hause fermentieren. Hygiene, Timing, Einsatz in Bigos und Pierogi.') on conflict (post_id, locale) do update set title = excluded.title, slug = excluded.slug, excerpt = excluded.excerpt, body = excluded.body, seo_title = excluded.seo_title, seo_description = excluded.seo_description;
insert into public.blog_post_translations (post_id, locale, title, slug, excerpt, body, seo_title, seo_description) values ('post-kiszenie', 'pl', 'Kiszenie w domu: kapusta, ogórki, czysta technika', 'kiszenie-w-domu', 'Fermentacja w niemieckim mieszkaniu: sól, temperatura, słoiki, bezpieczeństwo — i co robimy sami pod bigos.', 'Kiszenie to nie trend, lecz praktyczna technika, która świetnie działa w niemieckim mieszkaniu, jeśli zachowamy czystość i proporcje. Daje nam kapustę, ogórki i dodatki o wyraźnym smaku bez ciągłych zakupów.

## Sól, woda, czystość

My używamy czystych słoików, świeżych warzyw i soli bez dodatków przeciwzbrylających, jeśli przepis tego wymaga. Warzywa muszą pozostać pod zalewą; kontakt z powietrzem zwiększa ryzyko pleśni. Słoik stawiamy na talerzyku, bo fermentacja potrafi wypchnąć płyn.



![Danie z polskiej kuchni](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-ogorkowa/fe6aee59-9d09-475d-8464-4012dab7203a.webp)

## Obserwuj, nie zgaduj

Fermentacja pachnie kwaśno i świeżo, może musować, ale nie powinna budzić odrazy. My nie próbujemy produktu z widoczną pleśnią albo nietypowym zapachem. Po osiągnięciu smaku, który nam odpowiada, przenosimy słoik do lodówki. Temperatura kuchni w Niemczech zimą i latem będzie inna, więc czas z przepisu traktujemy jako orientacyjny.

## Jak używać

Kiszoną kapustę dodajemy do [bigosu](/pl/rezepte/bigos), do [kapuśniaka](/pl/rezepte/kapusniak), ciepłej [kapusty zasmażanej](/pl/rezepte/kapusta-zasmażana), farszu i surówek. Ogórki podajemy do obiadu albo gotujemy z nich [ogórkową](/pl/rezepte/ogorkowa); zalewę wykorzystujemy ostrożnie. My zaczynamy od małych słoików — łatwiej zrozumieć własną kuchnię niż zmarnować pięć litrów.



![Przygotowanie w kuchni diaspory](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-kapusniak/d602b625-35e3-4b65-88c1-1202fd7d9507.webp)

## FAQ — kiszenie

### Czy my zamykamy słoik bardzo szczelnie?

Na początku my zapewniamy bezpieczne ujście gazów zgodnie z wybraną metodą, a nie ryzykujemy nadciśnienia.

### Czy my możemy odciąć pleśń?

Nie. My przy widocznej pleśni wyrzucamy całość, bo bezpieczeństwo jest ważniejsze niż słoik warzyw.

### Czy my używamy zwykłej soli?

My sprawdzamy skład. Najprostsza sól jest najbardziej przewidywalna.

## Praktyka w niemieckiej kuchni

My nie potrzebujemy dużej przestrzeni, żeby gotować po polsku — potrzebujemy kolejności. Przed większym gotowaniem sprawdzamy, czy mamy wystarczająco misek, pojemników i miejsca w lodówce. W tygodniu roboczym w Niemczech lepiej działa jedno danie domowe niż trzy rozpoczęte i niedokończone projekty. My zapisujemy po obiedzie jedną rzecz do poprawy: mniej soli, wcześniejsze odsączenie, krótsze gotowanie, inna marka mąki. Ta notatka w telefonie bywa cenniejsza niż kolejny przepis z internetu.

Dzieci i goście wychowani w Niemczech często potrzebują łagodniejszej wersji tego samego dania — nie osobnego menu. My wydzielamy porcję przed doprawieniem ostrego garnka albo podajemy dodatki osobno. To nie kompromis tradycji; to sposób, by stół był gościnny. Gdy coś wychodzi inaczej niż „u babci”, nadal może być dobre, jeśli jest bezpieczne, czytelne w smaku i podane bez pośpiechu.', 'Kiszenie w domu | Poradnik | Alemniam', 'Kiszenie: kapusta i ogórki w domu. Higiena, czas, użycie w bigosie i pierogach.') on conflict (post_id, locale) do update set title = excluded.title, slug = excluded.slug, excerpt = excluded.excerpt, body = excluded.body, seo_title = excluded.seo_title, seo_description = excluded.seo_description;

commit;
