-- AUTO-GENERATED by scripts/generate-supabase-import.ts — do not edit by hand.
-- Regenerate after any seed*.ts content change: npx tsx scripts/generate-supabase-import.ts
begin;

-- blog:post-golabki-guide
insert into public.blog_posts (id, status, post_type, cover_image, silo_ids, related_recipe_ids, related_post_ids, related_product_ids, cluster_ids, published_at, updated_at) values ('post-golabki-guide', 'published', 'guide', 'https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/blog/post-golabki-guide/31857352-e3ef-43cd-8726-cc529a6dd790.webp', array['dishFamily']::text[], array['recipe-golabki', 'recipe-rosol', 'recipe-bigos']::text[], array['post-sonntagsessen', 'post-dutch-oven', 'post-smietana-schmand', 'post-rosol-technik', 'post-kasza']::text[], array['aff-dutch-oven']::text[], array['occasion-niedziela', 'technique-schmoren']::text[], '2026-07-25T09:00:00.000Z', '2026-07-21T12:00:00.000Z') on conflict (id) do update set status = excluded.status, post_type = excluded.post_type, cover_image = excluded.cover_image, silo_ids = excluded.silo_ids, related_recipe_ids = excluded.related_recipe_ids, related_post_ids = excluded.related_post_ids, related_product_ids = excluded.related_product_ids, cluster_ids = excluded.cluster_ids, published_at = excluded.published_at, updated_at = excluded.updated_at;
insert into public.blog_post_translations (post_id, locale, title, slug, excerpt, body, seo_title, seo_description) values ('post-golabki-guide', 'de', 'Gołąbki-Guide: Sonntag, Sauce und Batch', 'golabki-guide', 'Gołąbki am Tisch: Sauce-Wege, Varianten, Batch und typische Fehler — Mengen und Schritte im Rezept.', 'Gołąbki sind für viele von uns in Deutschland mehr als ein Kohlgericht: Sonntagsessen, Familientreffen, das Gericht, das nach dem ersten Biss nach Hause schmeckt. Mengen, Blanchierzeiten und die Schrittfolge stehen im [Gołąbki-Rezept](/de/rezepte/golabki). Hier geht es um den Platz am Tisch, Sauce-Entscheidungen, Varianten und Batch — ohne das Rezept zu wiederholen.

## Was Gołąbki sind

Gefüllte Kohlrouladen: biegsame Blätter, Reis-Fleisch-Füllung (oder vegetarisch), tragende Soße, langes sanftes Schmoren. In Polen oft neben [Rosół](/de/rezepte/rosol) und [Bigos](/de/rezepte/bigos); in der Diaspora das Gericht für Gäste oder die Woche im Voraus. Anders als manche deutsche Kohlroulade: oft feiner gewürzt, mehr Reis, Soße tomaten- oder brühebasiert. Manche servieren [Śmietana](/de/blog/smietana-schmand) — beides legitim, wenn der Kohl zart bleibt.



![Gericht aus der polnischen Küche](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-golabki/56ae4f6d-22d3-4bcd-9886-e71c4cba3244.webp)

## Sauce: drei Wege

**Tomate** — Diaspora-Klassiker: Farbe, Säure, Freezer-freundlich. **Rosół-Rest** — Tiefe ohne Tomatenrot; wer Sonntags [Rosół](/de/rezepte/rosol) kocht, plant Gołąbki oft für den Tag danach. Mehr zur Brühe steht in der [Rosół-Technik](/de/blog/rosol-technik). **Śmietana** — mild am Teller oder sparsam untergerührt; nicht kochend aufkochen. Details: [Śmietana vs. Schmand](/de/blog/smietana-schmand).

Entscheidend: genug Flüssigkeit, Rollen bedeckt, sanftes Köcheln — Details im Rezept.

## Varianten und Batch

Vegetarisch mit Pilzen oder Linsen; [Kasza gryczana](/de/blog/kasza-buchweizen) statt Reis — vorgegart, nicht zu nass. Gołąbki vertragen Anpassung, solange Kohl, Füllungsbalance und Schmorzeit stimmen.

Batch lohnt: ein Topf, viele Portionen; am nächsten Tag oft besser. Gekocht einfrieren mit Soße (2–3 Monate Qualität). Roh gefüllt frieren ist heikler — lieber durchkochen. Topf: [Dutch Oven](/de/blog/dutch-oven-kaufberatung) hilft, ist aber nicht Pflicht. Sonntagskontext: [polnisches Sonntagsessen](/de/blog/sonntagsessen-polnisch).

## Typische Fehler (über alle Hausrezepte)

- Zu straff gerollt oder zu nasser/roher Reis → Platzer
- Rippe nicht flach → hartes Kauen trotz langer Zeit
- Zu heftig kochen statt sanft → Soße trennt, Rollen springen
- Zu wenig Flüssigkeit → trockene Blätter oben
- Zu mageres Hack allein → trockene Füllung trotz weichem Kohl

Die Korrekturen und Mengen: [Gołąbki-Rezept](/de/rezepte/golabki).



![Zubereitung in der Diaspora-Küche](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-kapusta-zasmazana/c654bc3b-88e7-4165-aec5-c6ab3c83a573.webp)

## FAQ kurz

### Polenladen Pflicht?

Nein für den Einstieg. Weißkohl, Hack, Reis, Tomaten reichen aus dem Supermarkt. Polenladen später für Majoran-Note oder Śmietana.

### Tomate oder Rosół?

Geschmack und was im Kühlschrank steht. Manche mischen. Volumen und Salzbalance zählen mehr als Reinheit.

## Weiterlesen

- [Gołąbki Rezept](/de/rezepte/golabki)
- [Rosół](/de/rezepte/rosol) · [Rosół-Technik](/de/blog/rosol-technik)
- [Bigos](/de/rezepte/bigos)
- [Sonntagsessen](/de/blog/sonntagsessen-polnisch)
- [Dutch-Oven-Kaufberatung](/de/blog/dutch-oven-kaufberatung)
- [Śmietana vs. Schmand](/de/blog/smietana-schmand)', 'Gołąbki Guide | Sauce, Varianten, Batch | Alemniam', 'Gołąbki im Überblick: Tomate oder Rosół, vegetarisch, Freezer. Kochen mit Mengen im Gołąbki-Rezept.') on conflict (post_id, locale) do update set title = excluded.title, slug = excluded.slug, excerpt = excluded.excerpt, body = excluded.body, seo_title = excluded.seo_title, seo_description = excluded.seo_description;
insert into public.blog_post_translations (post_id, locale, title, slug, excerpt, body, seo_title, seo_description) values ('post-golabki-guide', 'pl', 'Przewodnik po gołąbkach: niedziela, sos, batch', 'golabki-przewodnik', 'Gołąbki przy stole: sosy, warianty, batch i typowe błędy — ilości i kroki w przepisie.', 'Gołąbki w diasporze często wracają w niedzielę albo przed wizytą rodziny — miękkie liście, soczysty farsz, sos, który trzyma całość. Ilości i kolejność kroków są w [przepisie na gołąbki](/pl/rezepte/golabki). Tutaj: miejsce przy stole, decyzje o sosie, warianty i batch — bez powtarzania przepisu.

## Co to są gołąbki

Zwinięte liście kapusty z farszem (ryż z mięsem, czasem kasza albo grzyby), duszone w sosie. Obok [rosołu](/pl/rezepte/rosol) i [bigosu](/pl/rezepte/bigos) bywają filarem niedzieli — szerszy kontekst: [obiad niedzielny](/pl/blog/obiad-niedzielny). To danie planu: raz wkład, wiele porcji.



![Danie z polskiej kuchni](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-golabki/56ae4f6d-22d3-4bcd-9886-e71c4cba3244.webp)

## Sos: trzy ścieżki

**Pomidor** — przewidywalny, dobrze znosi mrożenie. **Resztki rosołu** — głębszy, „niedzielny” smak; technika: [jak ugotować rosół](/pl/blog/jak-ugotowac-rosol). **Śmietana** — łagodniej; porównanie nabiału: [śmietana czy Schmand](/pl/blog/smietana-czy-schmand). Sos ma prawie zakrywać rolki — szczegóły w przepisie.

## Warianty i batch

Wege z grzybami lub soczewicą; [kasza gryczana](/pl/blog/kasza-gryczana) zamiast ryżu — ugotowana al dente, nie za mokra. Gołąbki lubią poprawki domu, byle kapusta, balans farszu i czas duszenia trzymały się razem.

Batch: duży garnek, porcje na tydzień; nazajutrz często lepiej. Ugotowane z sosem do zamrażarki. Surowe zwinięte mrozić ostrożniej — bezpieczniej ugotować. Garnek: [garnek do duszenia](/pl/blog/garnek-do-duszenia).

## Typowe błędy

- Za ciasno / za mokry lub surowy ryż → pękają
- Grube żyłki → „gryzą” mimo godzin w garnku
- Za gwałtowne gotowanie → sos i rolki cierpią
- Za mało płynu → suche brzegi
- Zbyt chude mięso → suchy farsz przy miękkiej kapuście

Korekty i ilości: [przepis gołąbki](/pl/rezepte/golabki).



![Przygotowanie w kuchni diaspory](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-kapusta-zasmazana/c654bc3b-88e7-4165-aec5-c6ab3c83a573.webp)

## FAQ krótko

### Czy kapusta tylko ze sklepu polskiego?

Nie. Biała z supermarketu zwykle wystarczy. Polski sklep — gdy są gotowe liście albo lepszy majeranek.

### Pomidor czy rosół?

Smak i to, co jest w lodówce. Można mieszać.

## Co czytać dalej

- [Przepis: gołąbki](/pl/rezepte/golabki)
- [Rosół](/pl/rezepte/rosol) · [jak ugotować rosół](/pl/blog/jak-ugotowac-rosol)
- [Bigos](/pl/rezepte/bigos)
- [Niedzielny obiad](/pl/blog/obiad-niedzielny)
- [Garnek do duszenia](/pl/blog/garnek-do-duszenia)
- [Śmietana czy Schmand](/pl/blog/smietana-czy-schmand)', 'Gołąbki przewodnik | Sos, warianty, batch | Alemniam', 'Przegląd gołąbków: pomidor lub rosół, wege, zamrażarka. Gotowanie z ilościami w przepisie na gołąbki.') on conflict (post_id, locale) do update set title = excluded.title, slug = excluded.slug, excerpt = excluded.excerpt, body = excluded.body, seo_title = excluded.seo_title, seo_description = excluded.seo_description;

commit;
