-- AUTO-GENERATED by scripts/generate-supabase-import.ts — do not edit by hand.
-- Regenerate after any seed*.ts content change: npx tsx scripts/generate-supabase-import.ts
begin;

-- blog:post-sylwester
insert into public.blog_posts (id, status, post_type, cover_image, silo_ids, related_recipe_ids, related_post_ids, related_product_ids, cluster_ids, published_at, updated_at) values ('post-sylwester', 'published', 'culture', 'https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/blog/post-sylwester/1afeec59-0661-4562-a8bb-79b91d527c95.webp', array['occasion', 'culture']::text[], array['recipe-sledz', 'recipe-salatka-sledziowa', 'recipe-tatar', 'recipe-zapiekanka', 'recipe-karp']::text[], array['post-hering', 'post-wigilia', 'post-kielbasa-arten', 'post-sonntagsessen']::text[], '{}'::text[], array['occasion-sylwester']::text[], '2026-08-23T13:10:00.000Z', '2026-08-23T13:10:00.000Z') on conflict (id) do update set status = excluded.status, post_type = excluded.post_type, cover_image = excluded.cover_image, silo_ids = excluded.silo_ids, related_recipe_ids = excluded.related_recipe_ids, related_post_ids = excluded.related_post_ids, related_product_ids = excluded.related_product_ids, cluster_ids = excluded.cluster_ids, published_at = excluded.published_at, updated_at = excluded.updated_at;
insert into public.blog_post_translations (post_id, locale, title, slug, excerpt, body, seo_title, seo_description) values ('post-sylwester', 'de', 'Sylwester Speiseplan: Hering um Mitternacht', 'silvester-speiseplan', 'Jahreswechsel ohne zweites Weihnachten: eine kalte Platte, optional Tartar, Zapiekanka in Chargen, Hygiene nach der Wigilia.', 'Sylwester in Deutschland ist selten eine Kopie der Wohnung, in der nach Mitternacht noch jemand Hering auf den Tisch stellte und niemand an Feuerwerk dachte. Es ist ein Abend zwischen Nachbarschaft, Balkonverbot, Schichtende und dem Wunsch, dass der Tisch um 23 Uhr noch trägt, ohne dass daraus ein zweites Weihnachten wird. Der Name meint den Jahreswechsel. Der Brauch meint mehr: Was bleibt kalt stehen, was darf roh sein, und wie viel Glückssymbol eine Küche nach der [Wigilia](/de/blog/wigilia-speiseplan) noch aushält.

Dieser Artikel ist der Speiseplan, nicht das Rezeptbuch. Mengen, Garzeiten und die konkrete Schrittfolge stehen in den einzelnen Rezepten. Hier ordnen wir, was den Mitternachtstisch trägt, was sich vorbereiten lässt und wo Haushalte in der Diaspora bewusst kürzen, ohne den Abend zu entwerten. Orientierung zu Hygiene, rohem Fleisch und Fisch: [bzfe.de](https://www.bzfe.de) und [ncez.pzh.gov.pl](https://ncez.pzh.gov.pl).

Historisch ist der polnische Sylwester jünger als die Wigilia und oft lauter. In vielen Häusern blieb trotzdem eine ruhige Linie: Hering fürs Geld im neuen Jahr, Brot, etwas Kaltes, kein Menümarathon nach zwölf Fastengängen. In Deutschland ersetzt das Feuerwerk den Tisch, und der Tisch verliert. Wir ersetzen den Beweisdruck durch einen ruhigen Plan. Eine klare Platte schlägt drei warme Pfannen, die um 0 Uhr niemand mehr führen will.

![Kalte Sylwesterplatte mit Hering, Brot und einer kleinen Schale Tartar](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/blog/post-sylwester/1afeec59-0661-4562-a8bb-79b91d527c95.webp "Eine klare Platte trägt Mitternacht besser als drei warme Pfannen.")

## Kein zweites Weihnachten

Weniger Linien, bessere Ausführung. Wigilia trägt den 24. [Sylwester](/de/anlaesse/silvester) trägt den 31. Wer am 31. noch Barszcz, Uszka, Karpfen und Kutia wiederholt, kocht Reste und Gereiztheit, nicht Glück. Reste vom Heiligabend dürfen auf den Tisch, wenn sie noch gut sind und ehrlich heißen.

Drei Blöcke reichen: kalt, eine optionale warme Kleinigkeit, Getränk. Kalt meint [Śledź](/de/rezepte/sledz), [Sałatka śledziowa](/de/rezepte/salatka-sledziowa), Brot, Gurken, optional [Tatar](/de/rezepte/tatar), wenn jemand ihn wirklich kann. Warm meint höchstens [Zapiekanka](/de/rezepte/zapiekanka) in Chargen oder Karpfenreste in der Pfanne.

Deutsche Gäste brauchen einen Satz: Nach Mitternacht gibt es Hering, das ist Glück, kein zweites Abendessen. Das ist Respekt, nicht Folklore.

## Hering um Mitternacht

Śledź um 0 Uhr ist in vielen Familien das einzige Pflichtsymbol. Eine Schale, Brot, Zwiebel. Wer den Unterschied zwischen Öl, Sahne und Salat erklären will, liest [Hering in Deutschland](/de/blog/hering-deutschland). Dieser Speiseplan sagt nur, wo der Fisch steht: bereit, kalt, in einer Menge, die nach dem Feuerwerk noch appetitlich bleibt.

Sałatka śledziowa trägt Gäste, die den puren Hering nicht wollen. Sie braucht Kälte und Zeit zum Durchziehen. Nicht um 23:30 erst anrühren.

Eine Sorte plus eine milde Linie reichen. Zwölf Fischschalen sind ein Buffet für Ostern, nicht für Mitternacht.

![Sałatka śledziowa kalt, bereit für Gäste](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-salatka-sledziowa/217de80a-a53b-4bc0-be52-f8f5b426a592.webp "Der Heringssalat trägt Gäste, die den puren Fisch nicht wollen.")

## Tartar oder weglassen

Tatar ist roh und damit eine eigene Hygieneaufgabe, kein Dekor. Wer ihn plant, kauft das Fleisch am selben Tag, hält es kalt, trennt Bretter, serviert klein und zeitnah. Schwangere, Kinder, ältere Gäste: eigene Entscheidung, sichtbare Alternative. Orientierung: [bzfe.de](https://www.bzfe.de).

Wer unsicher ist, lässt Tartar weg. Hering und Brot bleiben ein vollständiger Mitternachtstisch. Heldentum mit Hack, das seit Nachmittag warm steht, ist kein Glück.

## Warm nur in Chargen

Zapiekanka aus dem Ofen um 1 Uhr ist Freundlichkeit, wenn eine Person nur diese Linie führt. Sie ersetzt nicht die kalte Platte. [Kiełbasa](/de/blog/kielbasa-arten) vom [Grill](/de/blog/polnisch-grillen) auf dem Balkon um Mitternacht ist in vielen Häusern verboten und unfreundlich. Hausordnung lesen.

Karpfenreste vom 24. dürfen in die Pfanne, wenn Geruch und Kühlung stimmen. Bei Zweifel entsorgen. Der [Karpfen](/de/rezepte/karp) bleibt ein Wigilia-Fisch, kein Pflichtgang zum Jahreswechsel.

## Zeitplan rückwärts

Einen Tag vorher: Polenladen für Hering, Gurken, Brot, optional das Fleisch für Tartar erst am 31. REWE oder Kaufland für Zwiebel, Getränke, Eis, Müllbeutel. Kühlschrank leeren. Sałatka ansetzen, nicht erst nach dem Silvesteressen der Nachbarn.

Am 31. selbst: Platte kalt stellen, Brot schneiden, eine Person führt Getränke, eine die Platte. Wer um 22 Uhr noch eine warme Suppe ansetzt, weil der Abend sonst nicht festlich wirkt, zahlt mit Gereiztheit. Der Tisch gewinnt, wenn Mitternacht Tisch bleibt.

## Einkauf und Nachbarn

Listen nach Block schreiben. Was der Hering braucht, eine Zeile. Was Tartar braucht, eine eigene, nur wenn er wirklich kommt. Der [Polenladen](/de/blog/polenladen-einkaufen) trägt den Fisch. Der Supermarkt trägt Getränke und das Offensichtliche.

Rauch, Knaller, Balkon: Höflichkeit schlägt Brauch. Ein Heringsteller in der Wohnung ist legaler als Kohle um 0 Uhr. Deutsche Nachbarn brauchen keinen Heiligenkalender, sie brauchen Ruhe nach 22 Uhr in vielen Häusern.

## Kinder und gemischte Familien

Kinder brauchen Brot, etwas Mildes, Abstand zum rohen Fleisch. Hering in kleinen Stücken, nicht als Mutprobe. Tartar nicht auf denselben Teller. Allergien kennzeichnen.

In gemischten Familien ist Mitternacht oft Feuerwerk, nicht Fisch. Ein Satz reicht: Wir essen Hering, wer will. Pflichtglück zerstört den Abend.

## Hygiene und Reste

Rohes Fleisch, Fisch und Brot nicht auf demselben Brett. Nachfüllen aus dem Kühlschrank. Mayonnaise und Sahne nicht stundenlang auf der Heizung. Orientierung: [bzfe.de](https://www.bzfe.de) und [ncez.pzh.gov.pl](https://ncez.pzh.gov.pl).

Reste zeitnah essen. Tartar nicht als Frühstück aufheben, wenn er lange warm stand. Hering in Öl hält besser als der Salat. Beschriften. Bei Zweifel wegwerfen.

## Getränke und der Rest der Wohnung

Der Tisch braucht Wasser und etwas, das die Gäste kennen. Wodka ist in manchen Häusern Brauch, in anderen ein Streit. Kinder brauchen eine eigene Kanne. Zuckerhaltige Mixgetränke neben Sahnehering machen den Magen laut. Eine Linie Getränk plus Wasser reicht.

Müll, Glas, Ölreste: vor Mitternacht klären, nicht danach. Ein Eimer und Folie neben der Platte verhindern, dass der Teppich den Abend erinnert.

Wer allein hostet, kauft kleiner. Sechs Gäste brauchen keine Sylwesterplatte für zwanzig. Reste, die niemand um 2 Uhr will, sind kein Glück.

## Arbeit teilen

Eine Person führt die kalte Platte, eine die Getränke, eine die Tür und die Nachbarn. Tartar, wenn er kommt, hat eine eigene Person und ein eigenes Brett. In der Diaspora nach der Wigilia-Woche ist das die einzige Form, in der der 31. freundlich bleibt.

Vegetarische Gäste: Gurken, Brot, ein Salat ohne Fisch, optional Zapiekanka ohne Wurst. Eine Extra-Fleischshow nur für eine Person erschöpft meist alle.

## FAQ

### Muss um Mitternacht wirklich Hering auf den Tisch?

In vielen Familien ja, als Symbol, nicht als Menü. Eine Schale reicht. Wer keinen Fisch mag, isst Brot und einen anderen kalten Happen. Der Brauch bleibt, wenn jemand am Tisch den Namen sagt.

### Ist Tartar Pflicht für einen polnischen Sylwester?

Nein. Tartar ist eine Linie für Haushalte, die Rohfleisch sicher führen. Hering, Brot und ein Salat sind vollständig. Unsicherheit ist ein Grund zum Weglassen, kein Mangel an Treue.

### Dürfen Wigilia-Reste auf den Sylwestertisch?

Ja, wenn Kühlung und Geruch stimmen. Karpfen, Hering, Salat: ehrlich benennen. Was unsicher ist, entsorgen. Ein neuer Hering ist freundlicher als ein zweifelhafter Karpfen.

### Was tun, wenn Gäste ein warmes Essen erwarten?

Einen Satz vorher: kalte Platte, optional eine Kleinigkeit aus dem Ofen. Niemand muss um 0 Uhr schmoren. Zapiekanka in Chargen, wenn eine Person sie führt.

### Wie halten wir die Platte nach Mitternacht sicher?

Kleine Chargen, Nachfüllen aus der Kälte, Rohfleisch zeitnah. Bei Wärme und langem Stehen entsorgen. Rahmen: [bzfe.de](https://www.bzfe.de).

## Ohne Scham, mit Mitternacht

Gekaufter Hering, kein Tartar und ein Abend ohne Balkonfeuer sind in der Diaspora in Ordnung. Heldentum, das Nachbarn und die eigene Stimmung zerstört, ist kein Gewinn an Brauch. Vorher die Platte kalt stellen, die Linie wählen, die Kühlkette halten. Sylwester bleibt freundlich, wenn der Tisch das darf. Rahmen: [Silvester](/de/anlaesse/silvester).', 'Silvester Speiseplan | Hering Mitternacht | Alemniam', 'Sylwester in Deutschland: Śledź, Salat, optional Tartar. Speiseplan für Mitternacht, bilingual, machbar.') on conflict (post_id, locale) do update set title = excluded.title, slug = excluded.slug, excerpt = excluded.excerpt, body = excluded.body, seo_title = excluded.seo_title, seo_description = excluded.seo_description;
insert into public.blog_post_translations (post_id, locale, title, slug, excerpt, body, seo_title, seo_description) values ('post-sylwester', 'pl', 'Menu na sylwestra: śledź o północy', 'menu-sylwester', 'Zmiana roku bez drugich Świąt: zimna półmiska, opcjonalnie tatar, zapiekanka porcjami, higiena po Wigilii.', 'Sylwester w Niemczech rzadko jest kopią mieszkania, w którym po północy ktoś jeszcze stawiał śledzia i nikt nie myślał o fajerwerkach. To wieczór między sąsiadami, zakazem balkonu, końcem zmiany i życzeniem, żeby stół o 23 jeszcze niósł, bez drugich Świąt. Nazwa znaczy zmianę roku. Zwyczaj znaczy więcej: co zostaje zimne, co wolno podać surowe, i ile symbolu szczęścia kuchnia po [Wigilii](/pl/blog/menu-wigilijne) jeszcze wytrzymuje.

Ten artykuł jest planem menu, nie książką przepisów. Ilości, czasy i konkretna kolejność kroków są w pojedynczych przepisach. Tutaj porządkujemy, co niesie stół o północy, co da się przygotować i gdzie domy w diasporze świadomie skracają, nie odbierając wieczorowi wartości. Orientacja o higienie, surowym mięsie i rybie: [bzfe.de](https://www.bzfe.de) oraz [ncez.pzh.gov.pl](https://ncez.pzh.gov.pl).

Historycznie polski sylwester jest młodszy niż Wigilia i często głośniejszy. W wielu domach zostawała jednak spokojna linia: śledź na pieniądze w nowym roku, chleb, coś zimnego, bez maratonu dań po dwunastu postnych. W Niemczech fajerwerki zastępują stół, a stół przegrywa. Dowód zastępujemy spokojnym planem. Czytelna półmiska bije trzy ciepłe patelnie, których o 0 nikt już nie chce prowadzić.

![Zimna półmiska sylwestrowa ze śledziem, chlebem i małą miseczką tatara](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/blog/post-sylwester/1afeec59-0661-4562-a8bb-79b91d527c95.webp "Czytelna półmiska niesie północ lepiej niż trzy ciepłe patelnie.")

## Nie drugie święta

Mniej linii, lepsze wykonanie. Wigilia niesie 24. [Sylwester](/pl/anlaesse/sylwester) niesie 31. Kto 31. powtarza jeszcze barszcz, uszka, karpia i kutię, gotuje resztki i irytację, nie szczęście. Resztki z Wigilii mogą na stół, gdy są jeszcze dobre i uczciwie nazwane.

Trzy bloki wystarczą: zimne, opcjonalna ciepła drobnostka, napój. Zimne znaczy [śledź](/pl/rezepte/sledz), [sałatka śledziowa](/pl/rezepte/salatka-sledziowa), chleb, ogórki, opcjonalnie [tatar](/pl/rezepte/tatar), gdy ktoś naprawdę umie. Ciepłe znaczy najwyżej [zapiekanka](/pl/rezepte/zapiekanka) porcjami albo resztki karpia na patelni.

Niemieccy goście potrzebują zdania: Po północy jest śledź, to szczęście, nie drugi obiad. To szacunek, nie folklor.

## Śledź o północy

Śledź o 0 w wielu rodzinach jest jedynym obowiązkowym symbolem. Jedna miska, chleb, cebula. Kto chce różnicę oleju, śmietany i sałatki, czyta [śledź w Niemczech](/pl/blog/sledz-w-niemczech). Ten plan mówi tylko, gdzie stoi ryba: gotowa, zimna, w ilości, która po fajerwerkach jeszcze wygląda apetycznie.

Sałatka śledziowa niesie gości, którzy nie chcą czystego śledzia. Potrzebuje chłodu i czasu. Nie mieszamy jej o 23:30.

Jedna odmiana plus linia łagodna wystarczą. Dwanaście misek ryby to bufet wielkanocny, nie północ.

![Sałatka śledziowa zimna, gotowa dla gości](https://kdrbtwwhmzszzukcffsu.supabase.co/storage/v1/object/public/recipe-media/recipes/recipe-salatka-sledziowa/217de80a-a53b-4bc0-be52-f8f5b426a592.webp "Sałatka niesie gości, którzy nie chcą czystej ryby.")

## Tatar albo odpuścić

Tatar jest surowy i tym samym osobnym zadaniem higieny, nie dekoracją. Kto go planuje, kupuje mięso tego samego dnia, trzyma zimno, rozdziela deski, podaje mało i wkrótce. Ciąża, dzieci, starsi goście: własna decyzja, widoczna alternatywa. Orientacja: [bzfe.de](https://www.bzfe.de).

Kto niepewny, odpuszcza tatara. Śledź i chleb zostają pełnym stołem o północy. Bohaterstwo z mięsem, które od popołudnia stoi w cieple, nie jest szczęściem.

## Ciepło tylko porcjami

Zapiekanka z piekarnika o 1 jest uprzejmością, gdy jedna osoba prowadzi tylko tę linię. Nie zastępuje zimnej półmiski. [Kiełbasa](/pl/blog/rodzaje-kielbasy) z [grilla](/pl/blog/grill-po-polsku) na balkonie o północy w wielu domach jest zakazana i nieuprzejma. Czytamy regulamin.

Resztki karpia z 24. mogą na patelnię, gdy zapach i chłód się zgadzają. Przy wątpliwości wyrzucamy. [Karp](/pl/rezepte/karp) zostaje rybą wigilijną, nie obowiązkowym daniem noworocznym.

## Harmonogram od tyłu

Dzień wcześniej: sklep polski po śledzia, ogórki, chleb, opcjonalnie mięso na tatara dopiero 31. REWE albo Kaufland po cebulę, napoje, lód, worki. Opróżniamy lodówkę. Sałatkę zestawiamy, nie po silwestrowym obiedzie sąsiadów.

31. samego: półmiska na zimno, chleb pokrojony, jedna osoba napoje, jedna półmiskę. Kto o 22 stawia jeszcze ciepłą zupę, bo inaczej wieczór nie jest odświętny, płaci irytacją. Stół wygrywa, gdy północ zostaje stołem.

## Zakupy i sąsiedzi

Listy według bloku. Co potrzebuje śledź, jeden wiersz. Co tatar, osobny, tylko gdy naprawdę przyjdzie. [Sklep polski](/pl/blog/sklep-polski-zakupy) niesie rybę. Supermarket niesie napoje i oczywistości.

Dym, petardy, balkon: uprzejmość bije zwyczaj. Talerz śledzia w mieszkaniu jest legalniejszy niż węgiel o 0. Niemieccy sąsiedzi nie potrzebują kalendarza świętych, potrzebują ciszy po 22 w wielu domach.

## Dzieci i mieszane rodziny

Dzieci potrzebują chleba, czegoś łagodnego, dystansu do surowego mięsa. Śledź w małych kawałkach, nie jako próba odwagi. Tatar nie na ten sam talerz. Alergie oznaczamy.

W mieszanych rodzinach północ często znaczy fajerwerki, nie rybę. Wystarczy zdanie: Jemy śledzia, kto chce. Obowiązkowe szczęście psuje wieczór.

## Higiena i resztki

Surowego mięsa, ryby i chleba nie kładziemy na tej samej desce. Dokładamy z lodówki. Majonezu i śmietany nie zostawiamy godzinami na kaloryferze. Orientacja: [bzfe.de](https://www.bzfe.de) oraz [ncez.pzh.gov.pl](https://ncez.pzh.gov.pl).

Resztki jemy wkrótce. Tatara nie zostawiamy na śniadanie, gdy długo stał w cieple. Śledź w oleju trzyma się lepiej niż sałatka. Opisujemy. Przy wątpliwości wyrzucamy.

## Napoje i reszta mieszkania

Stół potrzebuje wody i czegoś, co goście znają. Wódka w jednych domach jest zwyczajem, w innych sporem. Dzieci potrzebują własnego dzbanka. Słodkie mixy obok śledzia w śmietanie robią żołądek głośnym. Jedna linia napoju plus woda wystarczą.

Śmieci, szkło, resztki oleju: przed północą, nie potem. Wiadro i folia obok półmiski zapobiegają temu, że dywan pamięta wieczór.

Kto hostuje sam, kupuje mniej. Sześciu gości nie potrzebuje półmiski na dwudziestu. Resztki, których nikt nie chce o 2, nie są szczęściem.

## Podział pracy

Jedna osoba prowadzi zimną półmiskę, jedna napoje, jedna drzwi i sąsiadów. Tatar, gdy przychodzi, ma własną osobę i własną deskę. W diasporze po tygodniu wigilijnym to jedyna forma, w której 31. zostaje przyjazny.

Goście wegetariańscy: ogórki, chleb, sałatka bez ryby, opcjonalnie zapiekanka bez kiełbasy. Extra pokaz mięsa tylko dla jednej osoby zwykle męczy wszystkich.

## FAQ

### Czy o północy naprawdę musi stanąć śledź?

W wielu rodzinach tak, jako symbol, nie jako menu. Jedna miska wystarczy. Kto nie lubi ryby, je chleb i inny zimny kęs. Zwyczaj zostaje, gdy ktoś przy stole mówi nazwę.

### Czy tatar jest obowiązkowy na polski sylwester?

Nie. Tatar to linia dla domów, które bezpiecznie prowadzą surowe mięso. Śledź, chleb i sałatka są pełne. Niepewność jest powodem do odpuszczenia, nie brakiem wierności.

### Czy resztki wigilijne mogą na stół sylwestrowy?

Tak, gdy chłód i zapach się zgadzają. Karp, śledź, sałatka: nazywamy uczciwie. Co niepewne, wyrzucamy. Nowy śledź jest przyjaźniejszy niż wątpliwy karp.

### Co zrobić, gdy goście czekają ciepłego jedzenia?

Zdanie wcześniej: zimna półmiska, opcjonalnie drobnostka z piekarnika. Nikt nie musi dusić o 0. Zapiekanka porcjami, gdy prowadzi ją jedna osoba.

### Jak bezpiecznie trzymać półmiskę po północy?

Małe porcje, dokładanie z chłodu, surowe mięso wkrótce. Przy cieple i długim staniu wyrzucamy. Ramy: [bzfe.de](https://www.bzfe.de).

## Bez wstydu, z północą

Kupiony śledź, bez tatara i wieczór bez ognia na balkonie są w diasporze w porządku. Bohaterstwo, które niszczy sąsiadów i własny nastrój, nie jest zyskiem zwyczaju. Wcześniej półmiska na zimno, wybrana linia, trzymany chłód. Sylwester zostaje przyjazny, gdy stół ma na to zgodę. Ramy: [Sylwester](/pl/anlaesse/sylwester).', 'Menu na sylwestra | Śledź o północy | Alemniam', 'Sylwester w Niemczech: śledź, sałatka, opcjonalnie tatar. Plan menu na północ, dwujęzycznie, wykonalnie.') on conflict (post_id, locale) do update set title = excluded.title, slug = excluded.slug, excerpt = excluded.excerpt, body = excluded.body, seo_title = excluded.seo_title, seo_description = excluded.seo_description;

commit;
